Const
 caAAA=0;                     { AAA, 8088+ }
 caAAD=1;                     { AAD, 8088+ }
 caAAM=2;                     { AAM, 8088+ }
 caAAS=3;                     { AAS, 8088+ }
 caADC=4;                     { ADC, 8088+ }
 caADD=5;                     { ADD, 8088+ }
 caAND=6;                     { AND, 8088+ }
 caARPL=7;                    { ARPL, 80286+ }
 caBOUND=8;                   { BOUND, 80186+ }
 caBSF=9;                     { BSF, 80386+ }
 caBSR=10;                    { BSR, 80386+ }
 caBSWAP=11;                  { BSWAP, 80486+ }
 caBT=12;                     { BT, 80386+ }
 caBTC=13;                    { BTC, 80386+ }
 caBTR=14;                    { BTR, 80386+ }
 caBTS=15;                    { BTS, 80386+ }
 caCALL=16;                   { CALL, 8088+ }
 caCBW=17;                    { CBW, 8088+ }
 caCDQ=18;                    { CDQ, 80386+ }
 caCLC=19;                    { CLC, 8088+ }
 caCLD=20;                    { CLD, 8088+ }
 caCLI=21;                    { CLI, 8088+ }
 caCLTS=22;                   { CLTS, 80286+ }
 caCMC=23;                    { CMC, 8088+ }
 caCMOVA=24;                  { CMOVA, 80686+ }
 caCMOVB=25;                  { CMOVB, 80686+ }
 caCMOVBE=26;                 { CMOVBE, 80686+ }
 caCMOVC=27;                  { CMOVC, 80686+ }
 caCMOVE=28;                  { CMOVE, 80686+ }
 caCMOVG=29;                  { CMOVG, 80686+ }
 caCMOVGE=30;                 { CMOVGE, 80686+ }
 caCMOVL=31;                  { CMOVL, 80686+ }
 caCMOVLE=32;                 { CMOVLE, 80686+ }
 caCMOVNA=33;                 { CMOVNA, 80686+ }
 caCMOVNAE=34;                { CMOVNAE, 80686+ }
 caCMOVNB=35;                 { CMOVNB, 80686+ }
 caCMOVNE=36;                 { CMOVNE, 80686+ }
 caCMOVNG=37;                 { CMOVNG, 80686+ }
 caCMOVNGE=38;                { CMOVNGE, 80686+ }
 caCMOVNL=39;                 { CMOVNL, 80686+ }
 caCMOVNO=40;                 { CMOVNO, 80686+ }
 caCMOVNP=41;                 { CMOVNP, 80686+ }
 caCMOVNS=42;                 { CMOVNS, 80686+ }
 caCMOVNZ=43;                 { CMOVNZ, 80686+ }
 caCMOVO=44;                  { CMOVO, 80686+ }
 caCMOVP=45;                  { CMOVP, 80686+ }
 caCMOVPE=46;                 { CMOVPE, 80686+ }
 caCMOVPO=47;                 { CMOVPO, 80686+ }
 caCMOVS=48;                  { CMOVS, 80686+ }
 caCMOVZ=49;                  { CMOVZ, 80686+ }
 caCMP=50;                    { CMP, 8088+ }
 caCMPSB=51;                  { CMPSB, 8088+ }
 caCMPSD=52;                  { CMPSD, 80386+ }
 caCMPSW=53;                  { CMPSW, 8088+ }
 caCMPXCHG=54;                { CMPXCHG, 80486+ }
 caCMPXCHG486=55;             { CMPXCHG486, 80486 }
 caCMPXCHG8B=56;              { CMPXCHG8B, 80486+ }
 caCPUID=57;                  { CPUID, 80586+ }
 caCS=58;                     { CS, 8088+ }
 caCWD=59;                    { CWD, 8088+ }
 caCWDE=60;                   { CWDE, 80386+ }
 caDAA=61;                    { DAA, 8088+ }
 caDAS=62;                    { DAS, 8088+ }
 caDB=63;                     { DB, 8088+ }
 caDD=64;                     { DD, 8088+ }
 caDEC=65;                    { DEC, 8088+ }
 caDIV=66;                    { DIV, 8088+ }
 caDQ=67;                     { DQ, 8088+ }
 caDS=68;                     { DS, 8088+ }
 caDW=69;                     { DW, 8088+ }
 caEMMS=70;                   { EMMS, MMX }
 caEND=71;                    { END, 8088+ }
 caENTER=72;                  { ENTER, 8088+ }
 caES=73;                     { ES, 8088+ }
 caESC=74;                    { ESC, 8088+ }
 caF2XM=75;                   { F2XM, 8087+ }
 caFABS=76;                   { FABS, 8087+ }
 caFADD=77;                   { FADD, 8087+ }
 caFADDF=78;                  { FADDF, 8087+ }
 caFBLD=79;                   { FBLD, 8087+ }
 caFBSTP=80;                  { FBSTP, 8087+ }
 caFCHS=81;                   { FCHS, 8087+ }
 caFCLEX=82;                  { FCLEX, 8087+ }
 caFCMOVB=83;                 { FCMOVB, 80686+ }
 caFCMOVBE=84;                { FCMOVBE, 80686+ }
 caFCMOVE=85;                 { FCMOVE, 80686+ }
 caFCMOVNB=86;                { FCMOVNB, 80686+ }
 caFCMOVNBE=87;               { FCMOVNBE, 80686+ }
 caFCMOVNE=88;                { FCMOVNE, 80686+ }
 caFCMOVNU=89;                { FCMOVNU, 80686+ }
 caFCMOVU=90;                 { FCMOVU, 80686+ }
 caFCOM=91;                   { FCOM, 8087+ }
 caFCOMI=92;                  { FCOMI, 80686+ }
 caFCOMIP=93;                 { FCOMIP, 80686+ }
 caFCOMP=94;                  { FCOMP, 8087+ }
 caFCOMPP=95;                 { FCOMPP, 8087+ }
 caFCOS=96;                   { FCOS, 8087+ }
 caFDECSTEP=97;               { FDECSTEP, 8087+ }
 caFDECSTP=98;                { FDECSTP, 8087+ }
 caFDISI=99;                  { FDISI, 8087+ }
 caFDIV=100;                  { FDIV, 8087+ }
 caFDIVP=101;                 { FDIVP, 8087+ }
 caFDIVR=102;                 { FDIVR, 8087+ }
 caFDIVRP=103;                { FDIVRP, 8087+ }
 caFENI=104;                  { FENI, 8087 }
 caFEXTRACT=105;              { FEXTRACT, 8087+ }
 caFFREE=106;                 { FFREE, 8087+ }
 caFIADD=107;                 { FIADD, 8087+ }
 caFICOM=108;                 { FICOM, 8087+ }
 caFICOMP=109;                { FICOMP, 8087+ }
 caFIDIV=110;                 { FIDIV, 8087+ }
 caFIDIVR=111;                { FIDIVR, 8087+ }
 caFILD=112;                  { FILD, 8087+ }
 caFIMUL=113;                 { FIMUL, 8087+ }
 caFIN=114;                   { FIN, 8088+ }
 caFINCSTEP=115;              { FINCSTEP, 8087+ }
 caFINCSTP=116;               { FINCSTP, 8087+ }
 caFINIT=117;                 { FINIT, 8087+ }
 caFISTP=118;                 { FISTP, 8087+ }
 caFISUB=119;                 { FISUB, 8087+ }
 caFISUBR=120;                { FISUBR, 8087+ }
 caFLOAT=121;                 { FLOAT, 8087+ }
 caFLOATABS=122;              { FLOATABS, 8087+ }
 caFLOATINIT=123;             { FLOATINIT, 8087+ }
 caFLOATNOP=124;              { FLOATNOP, 8087+ }
 caFLOATROUNDINTEGER=125;     { FLOATROUNDINTEGER, 8087+ }
 caFLD=126;                   { FLD, 8087+ }
 caFLD1=127;                  { FLD1, 8087+ }
 caFLDCW=128;                 { FLDCW, 8087+ }
 caFLDENV=129;                { FLDENV, 8087+ }
 caFLDL2E=130;                { FLDL2E, 8087+ }
 caFLDL2T=131;                { FLDL2T, 8087+ }
 caFLDLG2=132;                { FLDLG2, 8087+ }
 caFLDLN2=133;                { FLDLN2, 8087+ }
 caFLDPI=134;                 { FLDPI, 8087+ }
 caFLDZ=135;                  { FLDZ, 8087+ }
 caFMUL=136;                  { FMUL, 8087+ }
 caFMULP=137;                 { FMULP, 8087+ }
 caFNCLEX=138;                { FNCLEX, 8087+ }
 caFNDISI=139;                { FNDISI, 8087 }
 caFNENI=140;                 { FNENI, 8087 }
 caFNINIT=141;                { FNINIT, 8087+ }
 caFNOP=142;                  { FNOP, 8087+ }
 caFNSAVE=143;                { FNSAVE, 8087+ }
 caFNSTENV=144;               { FNSTENV, 8087+ }
 caFNSTCW=145;                { FNSTCW, 8087+ }
 caFNSTSW=146;                { FNSTSW, 8087+ }
 caFPATAN=147;                { FPATAN, 8087+ }
 caFPREM=148;                 { FPREM, 8087+ }
 caFPREM1=149;                { FPREM1, 80387+ }
 caFPTAN=150;                 { FPTAN, 8087+ }
 caFROUNDINTEGER=151;         { FROUNDINTEGER, 8087+ }
 caFRNDINT=152;               { FRNDINT, 8087+ }
 caFRSTOR=153;                { FRSTOR, 8087+ }
 caFS=154;                    { FS, 80386+ }
 caFSAVE=155;                 { FSAVE, 8087+ }
 caFSCALE=156;                { FSCALE, 8087+ }
 caFSETPM=157;                { FSETPM, 80387+ }
 caFSIN=158;                  { FSIN, 80387+ }
 caFSINCOS=159;               { FSINCOS, 80387+ }
 caFSQRT=160;                 { FSQRT, 8087+ }
 caFST=161;                   { FST, 8087+ }
 caFSTCW=162;                 { FSTCW, 8087+ }
 caFSTENV=163;                { FSTENV, 8087+ }
 caFSTP=164;                  { FSTP, 8087+ }
 caFSTSW=165;                 { FSTSW, 8087+ }
 caFSUB=166;                  { FSUB, 8087+ }
 caFSUBPP=167;                { FSUBPP, 8087+ }
 caFSUBR=168;                 { FSUBR, 8087+ }
 caFSUBRP=169;                { FSUBRP, 8087+ }
 caFTST=170;                  { FTST, 8087+ }
 caFUCOM=171;                 { FUCOM, 80387+ }
 caFUCOMI=172;                { FUCOMI, 80686+ }
 caFUCOMIP=173;               { FUCOMIP, 80686+ }
 caFUCOMP=174;                { FUCOMP, 80387+ }
 caFUCOMPP=175;               { FUCOMPP, 80387+ }
 caFWAIT=176;                 { FWAIT, 8087+ }
 caFXAM=177;                  { FXAM, 8087+ }
 caFXCH=178;                  { FXCH, 8087+ }
 caFXTRACT=179;               { FXTRACT, 8087+ }
 caFYL2X=180;                 { FYL2X, 8087+ }
 caFYL2XP1=181;               { FYL2XP1, 8087+ }
 caGS=182;                    { GS, 80386+ }
 caHALT=183;                  { HALT, 8088+ }
 caHLT=184;                   { HLT, 8088+ }
 caIBTS=185;                  { IBTS, 80386 }
 caICEBP=186;                 { ICEBP, 80686+ }
 caIDIV=187;                  { IDIV, 8088+ }
 caIF=188;                    { IF, 8088+ }
 caIMUL=189;                  { IMUL, 8088+ }
 caIN=190;                    { IN, 8088+ }
 caINC=191;                   { INC, 8088+ }
 caINSB=192;                  { INSB, 80286+ }
 caINSD=193;                  { INSD, 80386+ }
 caINSW=194;                  { INSW, 80286+ }
 caINT=195;                   { INT, 8088+ }
 caINT01=196;                 { INT01, 80686+ }
 caINT1=197;                  { INT1, 80686+ }
 caINT3=198;                  { INT3, 8088+ }
 caINTERRUPT=199;             { INTERRUPT, 8088+ }
 caINTERRUPTRETURN=200;       { INTERRUPTRETURN, 8088+ }
 caINTO=201;                  { INTO, 8088+ }
 caINVD=202;                  { INVD, 80486+ }
 caINVLPG=203;                { INVLPG, 80486+ }
 caIRET=204;                  { IRET, 8088+ }
 caIRETD=205;                 { IRETD, 80386+ }
 caIRETW=206;                 { IRETW, 8088+ }
 caJA=207;                    { JA, 8088+ }
 caJAE=208;                   { JAE, 8088+ }
 caJB=209;                    { JB, 8088+ }
 caJBE=210;                   { JBE, 8088+ }
 caJC=211;                    { JC, 8088+ }
 caJCXZ=212;                  { JCXZ, 8088+ }
 caJE=213;                    { JE, 8088+ }
 caJECXZ=214;                 { JECXZ, 80386+ }
 caJG=215;                    { JG, 8088+ }
 caJGE=216;                   { JGE, 8088+ }
 caJL=217;                    { JL, 8088+ }
 caJLE=218;                   { JLE, 8088+ }
 caJMP=219;                   { JMP, 8088+ }
 caJNA=220;                   { JNA, 8088+ }
 caJNAE=221;                  { JNAE, 8088+ }
 caJNB=222;                   { JNB, 8088+ }
 caJNC=223;                   { JNC, 8088+ }
 caJNE=224;                   { JNE, 8088+ }
 caJNG=225;                   { JNG, 8088+ }
 caJNGE=226;                  { JNGE, 8088+ }
 caJNL=227;                   { JNL, 8088+ }
 caJNLE=228;                  { JNLE, 8088+ }
 caJNO=229;                   { JNO, 8088+ }
 caJNP=230;                   { JNP, 8088+ }
 caJNS=231;                   { JNS, 8088+ }
 caJNZ=232;                   { JNZ, 8088+ }
 caJO=233;                    { JO, 8088+ }
 caJP=234;                    { JP, 8088+ }
 caJPE=235;                   { JPE, 8088+ }
 caJPO=236;                   { JPO, 8088+ }
 caJS=237;                    { JS, 8088+ }
 caJZ=238;                    { JZ, 8088+ }
 caLAHF=239;                  { LAHF, 8088+ }
 caLAR=240;                   { LAR, 80286+ }
 caLDS=241;                   { LDS, 8088+ }
 caLEA=242;                   { LEA, 8088+ }
 caLEAVE=243;                 { LEAVE, 80186+ }
 caLES=244;                   { LES, 8088+ }
 caLFS=245;                   { LFS, 80386+ }
 caLGDT=246;                  { LGDT, 80286+ }
 caLGS=247;                   { LGS, 80386+ }
 caLIDT=248;                  { LIDT, 80286+ }
 caLLDT=249;                  { LLDT, 80286+ }
 caLMSW=250;                  { LMSW, 80286+ }
 caLOADAHFLAGS=251;           { LOADAHFLAGS, 8088+ }
 caLOADALL=252;               { LOADALL, 80386 }
 caLOADALL286=253;            { LOADALL286, 80286 }
 caLOADSB=254;                { LOADSB, 8088+ }
 caLOADSD=255;                { LOADSD, 80386+ }
 caLOADSTRBYTE=256;           { LOADSTRBYTE, 8088+ }
 caLOADSTRDOUBLEWORD=257;     { LOADSTRDOUBLEWORD, 80386+ }
 caLOADSTRWORD=258;           { LOADSTRWORD, 8088+ }
 caLOADSW=259;                { LOADSW, 8088+ }
 caLOCK=260;                  { LOCK, 8088+ }
 caLODSB=261;                 { LODSB, 8088+ }
 caLODSD=262;                 { LODSD, 80386+ }
 caLODSW=263;                 { LODSW, 8088+ }
 caLOOP=264;                  { LOOP, 8088+ }
 caLOOPE=265;                 { LOOPE, 8088+ }
 caLOOPNE=266;                { LOOPNE, 8088+ }
 caLOOPNZ=267;                { LOOPNZ, 8088+ }
 caLOOPZ=268;                 { LOOPZ, 8088+ }
 caLSL=269;                   { LSL, 80286+ }
 caLSS=270;                   { LSS, 80386+ }
 caLTR=271;                   { LTR, 80286+ }
 caMOV=272;                   { MOV, 8088+ }
 caMOVD=273;                  { MOVD, MMX }
 caMOVQ=274;                  { MOVQ, MMX }
 caMOVSB=275;                 { MOVSB, 8088+ }
 caMOVSD=276;                 { MOVSD, 80386+ }
 caMOVSW=277;                 { MOVSW, 8088+ }
 caMOVSX=278;                 { MOVSX, 80386+ }
 caMOVZX=279;                 { MOVZX, 80386+ }
 caMUL=280;                   { MUL, 8088+ }
 caNEG=281;                   { NEG, 8088+ }
 caNOP=282;                   { NOP, 8088+ }
 caNOP386=283;                { NOP386, 80386+ }
 caNOT=284;                   { NOT, 8088+ }
 caOR=285;                    { OR, 8088+ }
 caOUT=286;                   { OUT, 8088+ }
 caOUTSB=287;                 { OUTSB, 80186+ }
 caOUTSD=288;                 { OUTSD, 80386+ }
 caOUTSW=289;                 { OUTSW, 80186+ }
 caPACKSSDW=290;              { PACKSSDW, MMX }
 caPACKSSWB=291;              { PACKSSWB, MMX }
 caPACKUSWB=292;              { PACKUSWB, MMX }
 caPADDB=293;                 { PADDB, MMX }
 caPADDD=294;                 { PADDD, MMX }
 caPADDSB=295;                { PADDSB, MMX }
 caPADDSW=296;                { PADDSW, MMX }
 caPADDUSB=297;               { PADDUSB, MMX }
 caPADDUSW=298;               { PADDUSW, MMX }
 caPADDW=299;                 { PADDW, MMX }
 caPAND=300;                  { PAND, MMX }
 caPANDN=301;                 { PANDN, MMX }
 caPADDSIW=302;               { PADDSIW, MMX }
 caPAVEB=303;                 { PAVEB, MMX }
 caPCMPEQB=304;               { PCMPEQB, MMX }
 caPCMPEQD=305;               { PCMPEQD, MMX }
 caPCMPEQW=306;               { PCMPEQW, MMX }
 caPCMPGTB=307;               { PCMPGTB, MMX }
 caPCMPGTD=308;               { PCMPGTD, MMX }
 caPCMPGTW=309;               { PCMPGTW, MMX }
 caPDISTIB=310;               { PDISTIB, MMX }
 caPMACHRIW=311;              { PMACHRIW, MMX }
 caPMADDWD=312;               { PMADDWD, MMX }
 caPMAGW=313;                 { PMAGW, MMX }
 caPMULHRW=314;               { PMULHRW, MMX }
 caPMULHRIW=315;              { PMULHRIW, MMX }
 caPMULHW=316;                { PMULHW, MMX }
 caPMVZB=317;                 { PMVZB, MMX }
 caPMVNZB=318;                { PMVNZB, MMX }
 caPMVLZB=319;                { PMVLZB, MMX }
 caPMVGEZB=320;               { PMVGEZB, MMX }
 caPOP=321;                   { POP, 8088+ }
 caPOPA=322;                  { POPA, 80286+ }
 caPOPAD=323;                 { POPAD, 80386+ }
 caPOPALL=324;                { POPALL, 80286+ }
 caPOPAW=325;                 { POPAW, 80286+ }
 caPOPF=326;                  { POPF, 8088+ }
 caPOPFD=327;                 { POPFD, 80386+ }
 caPOPFLAGS=328;              { POPFLAGS, 8088+ }
 caPOPFW=329;                 { POPFW, 8088+ }
 caPOR=330;                   { POR, MMX }
 caPSLLD=331;                 { PSLLD, MMX }
 caPSLLQ=332;                 { PSLLQ, MMX }
 caPSLLW=333;                 { PSLLW, MMX }
 caPSRAD=334;                 { PSRAD, MMX }
 caPSRAW=335;                 { PSRAW, MMX }
 caPSRLD=336;                 { PSRLD, MMX }
 caPSRLQ=337;                 { PSRLQ, MMX }
 caPSRLW=338;                 { PSRLW, MMX }
 caPSUBB=339;                 { PSUBB, MMX }
 caPSUBD=340;                 { PSUBD, MMX }
 caPSUBSB=341;                { PSUBSB, MMX }
 caPSUBSIW=342;               { PSUBSIW, MMX }
 caPSUBSW=343;                { PSUBSW, MMX }
 caPSUBUSB=344;               { PSUBUSB, MMX }
 caPSUBUSW=345;               { PSUBUSW, MMX }
 caPSUBW=346;                 { PSUBW, MMX }
 caPUNPCKHBW=347;             { PUNPCKHBW, MMX }
 caPUNPCKHWD=348;             { PUNPCKHWD, MMX }
 caPUNPCKHDQ=349;             { PUNPCKHDQ, MMX }
 caPUNPCKLBW=350;             { PUNPCKLBW, MMX }
 caPUNPCKLWD=351;             { PUNPCKLWD, MMX }
 caPUNPCKLDQ=352;             { PUNPCKLDQ, MMX }
 caPUSH=353;                  { PUSH, 8088+ }
 caPUSHA=354;                 { PUSHA, 80286+ }
 caPUSHAD=355;                { PUSHAD, 80386+ }
 caPUSHALL=356;               { PUSHALL, 80286+ }
 caPUSHAW=357;                { PUSHAW, 80286+ }
 caPUSHF=358;                 { PUSHF, 8088+ }
 caPUSHFD=359;                { PUSHFD, 80386+ }
 caPUSHFLAGS=360;             { PUSHFLAGS, 8088+ }
 caPUSHFW=361;                { PUSHFW, 8088+ }
 caPXOR=362;                  { PXOR, MMX }
 caRCL=363;                   { RCL, 8088+ }
 caRCR=364;                   { RCR, 8088+ }
 caRDMSR=365;                 { RDMSR, 80586+ }
 caRDPMC=366;                 { RDPMC, 80686+ }
 caRDTSC=367;                 { RDTSC, 80586+ }
 caREP=368;                   { REP, 8088+ }
 caREPE=369;                  { REPE, 8088+ }
 caREPNE=370;                 { REPNE, 8088+ }
 caREPNZ=371;                 { REPNZ, 8088+ }
 caREPZ=372;                  { REPZ, 8088+ }
 caRET=373;                   { RET, 8088+ }
 caRETF=374;                  { RETF, 8088+ }
 caRETN=375;                  { RETN, 8088+ }
 caROL=376;                   { ROL, 8088+ }
 caROR=377;                   { ROR, 8088+ }
 caRSM=378;                   { RSM, 80586+ }
 caSAHF=379;                  { SAHF, 8088+ }
 caSAL=380;                   { SAL, 8088+ }
 caSALC=381;                  { SALC, 8088+ }
 caSAR=382;                   { SAR, 8088+ }
 caSAVEAHFLAGS=383;           { SAVEAHFLAGS, 8088+ }
 caSBB=384;                   { SBB, 8088+ }
 caSCASB=385;                 { SCASB, 8088+ }
 caSCASD=386;                 { SCASD, 80386+ }
 caSCASW=387;                 { SCASW, 8088+ }
 caSETA=388;                  { SETA, 80386+ }
 caSETAE=389;                 { SETAE, 80386+ }
 caSETALC=390;                { SETALC, 8088+ }
 caSETB=391;                  { SETB, 80386+ }
 caSETBE=392;                 { SETBE, 80386+ }
 caSETC=393;                  { SETC, 80386+ }
 caSETCARRY=394;              { SETCARRY, 8088+ }
 caSETCF=395;                 { SETCF, 8088+ }
 caSETD=396;                  { SETD, 8088+ }
 caSETDF=397;                 { SETDF, 8088+ }
 caSETE=398;                  { SETE, 80386+ }
 caSETG=399;                  { SETG, 80386+ }
 caSETGE=400;                 { SETGE, 80386+ }
 caSETI=401;                  { SETI, 8088+ }
 caSETIF=402;                 { SETIF, 8088+ }
 caSETL=403;                  { SETL, 80386+ }
 caSETLE=404;                 { SETLE, 80386+ }
 caSETNA=405;                 { SETNA, 80386+ }
 caSETNAE=406;                { SETNAE, 80386+ }
 caSETNB=407;                 { SETNB, 80386+ }
 caSETNC=408;                 { SETNC, 80386+ }
 caSETNE=409;                 { SETNE, 80386+ }
 caSETNG=410;                 { SETNG, 80386+ }
 caSETNGE=411;                { SETNGE, 80386+ }
 caSETNL=412;                 { SETNL, 80386+ }
 caSETNLE=413;                { SETNLE, 80386+ }
 caSETNO=414;                 { SETNO, 80386+ }
 caSETNP=415;                 { SETNP, 80386+ }
 caSETNS=416;                 { SETNS, 80386+ }
 caSETNZ=417;                 { SETNZ, 80386+ }
 caSETO=418;                  { SETO, 80386+ }
 caSETP=419;                  { SETP, 80386+ }
 caSETPE=420;                 { SETPE, 80386+ }
 caSETPO=421;                 { SETPO, 80386+ }
 caSETS=422;                  { SETS, 80386+ }
 caSETZ=423;                  { SETZ, 80386+ }
 caSGDT=424;                  { SGDT, 80286+ }
 caSHL=425;                   { SHL, 8088+ }
 caSHLD=426;                  { SHLD, 80386+ }
 caSHR=427;                   { SHR, 8088+ }
 caSHRD=428;                  { SHRD, 80386+ }
 caSIDT=429;                  { SIDT, 80286+ }
 caSLDT=430;                  { SLDT, 80286+ }
 caSMI=431;                   { SMI, 80386+ }
 caSS=432;                    { SS, 8088+ }
 caSTC=433;                   { STC, 8088+ }
 caSTD=434;                   { STD, 8088+ }
 caSTI=435;                   { STI, 8088+ }
 caSTOSB=436;                 { STOSB, 8088+ }
 caSTOSD=437;                 { STOSD, 80386+ }
 caSTOSW=438;                 { STOSW, 8088+ }
 caSTR=439;                   { STR, 80286+ }
 caSUB=440;                   { SUB, 8088+ }
 caTEST=441;                  { TEST, 8088+ }
 caUMOV=442;                  { UMOV, 80386 }
 caVERR=443;                  { VERR, 80286+ }
 caVERW=444;                  { VERW, 80286+ }
 caWAIT=445;                  { WAIT, 8088+ }
 caWBINVD=446;                { WBINVD, 80486+ }
 caWRMSR=447;                 { WRMSR, 80586+ }
 caXADD=448;                  { XADD, 80486+ }
 caXBTS=449;                  { XBTS, 80386 }
 caXCHG=450;                  { XCHG, 8088+ }
 caXLAT=451;                  { XLAT, 8088+ }
 caXLATB=452;                 { XLATB, 8088+ }
 caXOR=453;                   { XOR, 8088+ }

  { Les constantes suivantes renferme l'arbre des }
  { pour connaŒtre les instructions assembleur }

 acAAD:NoeudAsmRec=(
  Nom:'AAD';
  Code:caAAD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D5#$0A;
  Gauche:0;
  Droite:0
 );

 acAAA:NoeudAsmRec=(
  Nom:'AAA';
  Code:caAAA;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$37;
  Gauche:0;
  Droite:Ofs(acAAD)
 );

 acAAS:NoeudAsmRec=(
  Nom:'AAS';
  Code:caAAS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$3F;
  Gauche:0;
  Droite:0
 );

 acADD:NoeudAsmRec=(
  Nom:'ADD';
  Code:caADD;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$00;
  Gauche:0;
  Droite:0
 );

 acADC:NoeudAsmRec=(
  Nom:'ADC';
  Code:caADC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$10;
  Gauche:Ofs(acAAS);
  Droite:Ofs(acADD)
 );

 acAAM:NoeudAsmRec=(
  Nom:'AAM';
  Code:caAAM;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D4#$0A;
  Gauche:Ofs(acAAA);
  Droite:Ofs(acADC)
 );

 acBOUND:NoeudAsmRec=(
  Nom:'BOUND';
  Code:caBOUND;
  CPU:p80186Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acARPL:NoeudAsmRec=(
  Nom:'ARPL';
  Code:caARPL;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acBOUND)
 );

 acBSR:NoeudAsmRec=(
  Nom:'BSR';
  Code:caBSR;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acBT:NoeudAsmRec=(
  Nom:'BT';
  Code:caBT;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acBSWAP:NoeudAsmRec=(
  Nom:'BSWAP';
  Code:caBSWAP;
  CPU:p80486Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acBSR);
  Droite:Ofs(acBT)
 );

 acBSF:NoeudAsmRec=(
  Nom:'BSF';
  Code:caBSF;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acARPL);
  Droite:Ofs(acBSWAP)
 );

 acAND:NoeudAsmRec=(
  Nom:'AND';
  Code:caAND;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$20;
  Gauche:Ofs(acAAM);
  Droite:Ofs(acBSF)
 );

 acBTS:NoeudAsmRec=(
  Nom:'BTS';
  Code:caBTS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acBTR:NoeudAsmRec=(
  Nom:'BTR';
  Code:caBTR;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acBTS)
 );

 acCBW:NoeudAsmRec=(
  Nom:'CBW';
  Code:caCBW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$98;
  Gauche:0;
  Droite:0
 );

 acCLC:NoeudAsmRec=(
  Nom:'CLC';
  Code:caCLC;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F8;
  Gauche:0;
  Droite:0
 );

 acCDQ:NoeudAsmRec=(
  Nom:'CDQ';
  Code:caCDQ;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$99;
  Gauche:Ofs(acCBW);
  Droite:Ofs(acCLC)
 );

 acCALL:NoeudAsmRec=(
  Nom:'CALL';
  Code:caCALL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acBTR);
  Droite:Ofs(acCDQ)
 );

 acCLTS:NoeudAsmRec=(
  Nom:'CLTS';
  Code:caCLTS;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$0F#$06;
  Gauche:0;
  Droite:0
 );

 acCLI:NoeudAsmRec=(
  Nom:'CLI';
  Code:caCLI;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FA;
  Gauche:0;
  Droite:Ofs(acCLTS)
 );

 acCMOVA:NoeudAsmRec=(
  Nom:'CMOVA';
  Code:caCMOVA;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$47;
  Gauche:0;
  Droite:0
 );

 acCMOVBE:NoeudAsmRec=(
  Nom:'CMOVBE';
  Code:caCMOVBE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$46;
  Gauche:0;
  Droite:0
 );

 acCMOVB:NoeudAsmRec=(
  Nom:'CMOVB';
  Code:caCMOVB;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$42;
  Gauche:Ofs(acCMOVA);
  Droite:Ofs(acCMOVBE)
 );

 acCMC:NoeudAsmRec=(
  Nom:'CMC';
  Code:caCMC;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F5;
  Gauche:Ofs(acCLI);
  Droite:Ofs(acCMOVB)
 );

 acCLD:NoeudAsmRec=(
  Nom:'CLD';
  Code:caCLD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FC;
  Gauche:Ofs(acCALL);
  Droite:Ofs(acCMC)
 );

 acBTC:NoeudAsmRec=(
  Nom:'BTC';
  Code:caBTC;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acAND);
  Droite:Ofs(acCLD)
 );

 acCMOVG:NoeudAsmRec=(
  Nom:'CMOVG';
  Code:caCMOVG;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4F;
  Gauche:0;
  Droite:0
 );

 acCMOVE:NoeudAsmRec=(
  Nom:'CMOVE';
  Code:caCMOVE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$44;
  Gauche:0;
  Droite:Ofs(acCMOVG)
 );

 acCMOVL:NoeudAsmRec=(
  Nom:'CMOVL';
  Code:caCMOVL;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4C;
  Gauche:0;
  Droite:0
 );

 acCMOVNA:NoeudAsmRec=(
  Nom:'CMOVNA';
  Code:caCMOVNA;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$46;
  Gauche:0;
  Droite:0
 );

 acCMOVLE:NoeudAsmRec=(
  Nom:'CMOVLE';
  Code:caCMOVLE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4E;
  Gauche:Ofs(acCMOVL);
  Droite:Ofs(acCMOVNA)
 );

 acCMOVGE:NoeudAsmRec=(
  Nom:'CMOVGE';
  Code:caCMOVGE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4D;
  Gauche:Ofs(acCMOVE);
  Droite:Ofs(acCMOVLE)
 );

 acCMOVNE:NoeudAsmRec=(
  Nom:'CMOVNE';
  Code:caCMOVNE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$45;
  Gauche:0;
  Droite:0
 );

 acCMOVNB:NoeudAsmRec=(
  Nom:'CMOVNB';
  Code:caCMOVNB;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$43;
  Gauche:0;
  Droite:Ofs(acCMOVNE)
 );

 acCMOVNGE:NoeudAsmRec=(
  Nom:'CMOVNGE';
  Code:caCMOVNGE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4C;
  Gauche:0;
  Droite:0
 );

 acCMOVNO:NoeudAsmRec=(
  Nom:'CMOVNO';
  Code:caCMOVNO;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$41;
  Gauche:0;
  Droite:0
 );

 acCMOVNL:NoeudAsmRec=(
  Nom:'CMOVNL';
  Code:caCMOVNL;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4D;
  Gauche:Ofs(acCMOVNGE);
  Droite:Ofs(acCMOVNO)
 );

 acCMOVNG:NoeudAsmRec=(
  Nom:'CMOVNG';
  Code:caCMOVNG;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4E;
  Gauche:Ofs(acCMOVNB);
  Droite:Ofs(acCMOVNL)
 );

 acCMOVNAE:NoeudAsmRec=(
  Nom:'CMOVNAE';
  Code:caCMOVNAE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$42;
  Gauche:Ofs(acCMOVGE);
  Droite:Ofs(acCMOVNG)
 );

 acCMOVNZ:NoeudAsmRec=(
  Nom:'CMOVNZ';
  Code:caCMOVNZ;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$45;
  Gauche:0;
  Droite:0
 );

 acCMOVNS:NoeudAsmRec=(
  Nom:'CMOVNS';
  Code:caCMOVNS;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$49;
  Gauche:0;
  Droite:Ofs(acCMOVNZ)
 );

 acCMOVP:NoeudAsmRec=(
  Nom:'CMOVP';
  Code:caCMOVP;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4A;
  Gauche:0;
  Droite:0
 );

 acCMOVPO:NoeudAsmRec=(
  Nom:'CMOVPO';
  Code:caCMOVPO;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4B;
  Gauche:0;
  Droite:0
 );

 acCMOVPE:NoeudAsmRec=(
  Nom:'CMOVPE';
  Code:caCMOVPE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4A;
  Gauche:Ofs(acCMOVP);
  Droite:Ofs(acCMOVPO)
 );

 acCMOVO:NoeudAsmRec=(
  Nom:'CMOVO';
  Code:caCMOVO;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$40;
  Gauche:Ofs(acCMOVNS);
  Droite:Ofs(acCMOVPE)
 );

 acCMP:NoeudAsmRec=(
  Nom:'CMP';
  Code:caCMP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$38;
  Gauche:0;
  Droite:0
 );

 acCMOVZ:NoeudAsmRec=(
  Nom:'CMOVZ';
  Code:caCMOVZ;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$45;
  Gauche:0;
  Droite:Ofs(acCMP)
 );

 acCMPSD:NoeudAsmRec=(
  Nom:'CMPSD';
  Code:caCMPSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$A7;
  Gauche:0;
  Droite:0
 );

 acCMPXCHG:NoeudAsmRec=(
  Nom:'CMPXCHG';
  Code:caCMPXCHG;
  CPU:p80486Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acCMPSW:NoeudAsmRec=(
  Nom:'CMPSW';
  Code:caCMPSW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$A7;
  Gauche:Ofs(acCMPSD);
  Droite:Ofs(acCMPXCHG)
 );

 acCMPSB:NoeudAsmRec=(
  Nom:'CMPSB';
  Code:caCMPSB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$A6;
  Gauche:Ofs(acCMOVZ);
  Droite:Ofs(acCMPSW)
 );

 acCMOVS:NoeudAsmRec=(
  Nom:'CMOVS';
  Code:caCMOVS;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$48;
  Gauche:Ofs(acCMOVO);
  Droite:Ofs(acCMPSB)
 );

 acCMOVNP:NoeudAsmRec=(
  Nom:'CMOVNP';
  Code:caCMOVNP;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$4B;
  Gauche:Ofs(acCMOVNAE);
  Droite:Ofs(acCMOVS)
 );

 acCMOVC:NoeudAsmRec=(
  Nom:'CMOVC';
  Code:caCMOVC;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:#$0F#$42;
  Gauche:Ofs(acBTC);
  Droite:Ofs(acCMOVNP)
 );

 acCPUID:NoeudAsmRec=(
  Nom:'CPUID';
  Code:caCPUID;
  CPU:p80586Plus;
  Parameters:No;
  OpCode:#$0F#$A2;
  Gauche:0;
  Droite:0
 );

 acCMPXCHG8B:NoeudAsmRec=(
  Nom:'CMPXCHG8B';
  Code:caCMPXCHG8B;
  CPU:p80486Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acCPUID)
 );

 acCWD:NoeudAsmRec=(
  Nom:'CWD';
  Code:caCWD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$99;
  Gauche:0;
  Droite:0
 );

 acDAA:NoeudAsmRec=(
  Nom:'DAA';
  Code:caDAA;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$27;
  Gauche:0;
  Droite:0
 );

 acCWDE:NoeudAsmRec=(
  Nom:'CWDE';
  Code:caCWDE;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$98;
  Gauche:Ofs(acCWD);
  Droite:Ofs(acDAA)
 );

 acCS:NoeudAsmRec=(
  Nom:'CS';
  Code:caCS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$2E;
  Gauche:Ofs(acCMPXCHG8B);
  Droite:Ofs(acCWDE)
 );

 acDD:NoeudAsmRec=(
  Nom:'DD';
  Code:caDD;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acDB:NoeudAsmRec=(
  Nom:'DB';
  Code:caDB;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acDD)
 );

 acDIV:NoeudAsmRec=(
  Nom:'DIV';
  Code:caDIV;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F0;
  Gauche:0;
  Droite:0
 );

 acDS:NoeudAsmRec=(
  Nom:'DS';
  Code:caDS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$3E;
  Gauche:0;
  Droite:0
 );

 acDQ:NoeudAsmRec=(
  Nom:'DQ';
  Code:caDQ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acDIV);
  Droite:Ofs(acDS)
 );

 acDEC:NoeudAsmRec=(
  Nom:'DEC';
  Code:caDEC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acDB);
  Droite:Ofs(acDQ)
 );

 acDAS:NoeudAsmRec=(
  Nom:'DAS';
  Code:caDAS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$2F;
  Gauche:Ofs(acCS);
  Droite:Ofs(acDEC)
 );

 acEND:NoeudAsmRec=(
  Nom:'END';
  Code:caEND;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acEMMS:NoeudAsmRec=(
  Nom:'EMMS';
  Code:caEMMS;
  CPU:pMMX;
  Parameters:No;
  OpCode:#$0F#$77;
  Gauche:0;
  Droite:Ofs(acEND)
 );

 acES:NoeudAsmRec=(
  Nom:'ES';
  Code:caES;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$26;
  Gauche:0;
  Droite:0
 );

 acF2XM:NoeudAsmRec=(
  Nom:'F2XM';
  Code:caF2XM;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F0;
  Gauche:0;
  Droite:0
 );

 acESC:NoeudAsmRec=(
  Nom:'ESC';
  Code:caESC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acES);
  Droite:Ofs(acF2XM)
 );

 acENTER:NoeudAsmRec=(
  Nom:'ENTER';
  Code:caENTER;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acEMMS);
  Droite:Ofs(acESC)
 );

 acFADDF:NoeudAsmRec=(
  Nom:'FADDF';
  Code:caFADDF;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFADD:NoeudAsmRec=(
  Nom:'FADD';
  Code:caFADD;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFADDF)
 );

 acFBSTP:NoeudAsmRec=(
  Nom:'FBSTP';
  Code:caFBSTP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCLEX:NoeudAsmRec=(
  Nom:'FCLEX';
  Code:caFCLEX;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$9B#$DB#$E2;
  Gauche:0;
  Droite:0
 );

 acFCHS:NoeudAsmRec=(
  Nom:'FCHS';
  Code:caFCHS;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E0;
  Gauche:Ofs(acFBSTP);
  Droite:Ofs(acFCLEX)
 );

 acFBLD:NoeudAsmRec=(
  Nom:'FBLD';
  Code:caFBLD;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFADD);
  Droite:Ofs(acFCHS)
 );

 acFABS:NoeudAsmRec=(
  Nom:'FABS';
  Code:caFABS;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E1;
  Gauche:Ofs(acENTER);
  Droite:Ofs(acFBLD)
 );

 acDW:NoeudAsmRec=(
  Nom:'DW';
  Code:caDW;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acDAS);
  Droite:Ofs(acFABS)
 );

 acFCMOVE:NoeudAsmRec=(
  Nom:'FCMOVE';
  Code:caFCMOVE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCMOVBE:NoeudAsmRec=(
  Nom:'FCMOVBE';
  Code:caFCMOVBE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFCMOVE)
 );

 acFCMOVNBE:NoeudAsmRec=(
  Nom:'FCMOVNBE';
  Code:caFCMOVNBE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCMOVNU:NoeudAsmRec=(
  Nom:'FCMOVNU';
  Code:caFCMOVNU;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCMOVNE:NoeudAsmRec=(
  Nom:'FCMOVNE';
  Code:caFCMOVNE;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFCMOVNBE);
  Droite:Ofs(acFCMOVNU)
 );

 acFCMOVNB:NoeudAsmRec=(
  Nom:'FCMOVNB';
  Code:caFCMOVNB;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFCMOVBE);
  Droite:Ofs(acFCMOVNE)
 );

 acFCOMI:NoeudAsmRec=(
  Nom:'FCOMI';
  Code:caFCOMI;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCOM:NoeudAsmRec=(
  Nom:'FCOM';
  Code:caFCOM;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFCOMI)
 );

 acFCOMP:NoeudAsmRec=(
  Nom:'FCOMP';
  Code:caFCOMP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFCOS:NoeudAsmRec=(
  Nom:'FCOS';
  Code:caFCOS;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FF;
  Gauche:0;
  Droite:0
 );

 acFCOMPP:NoeudAsmRec=(
  Nom:'FCOMPP';
  Code:caFCOMPP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$DE#$D9;
  Gauche:Ofs(acFCOMP);
  Droite:Ofs(acFCOS)
 );

 acFCOMIP:NoeudAsmRec=(
  Nom:'FCOMIP';
  Code:caFCOMIP;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFCOM);
  Droite:Ofs(acFCOMPP)
 );

 acFCMOVU:NoeudAsmRec=(
  Nom:'FCMOVU';
  Code:caFCMOVU;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFCMOVNB);
  Droite:Ofs(acFCOMIP)
 );

 acFDISI:NoeudAsmRec=(
  Nom:'FDISI';
  Code:caFDISI;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$9B#$DB#$E1;
  Gauche:0;
  Droite:0
 );

 acFDECSTP:NoeudAsmRec=(
  Nom:'FDECSTP';
  Code:caFDECSTP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F6;
  Gauche:0;
  Droite:Ofs(acFDISI)
 );

 acFDIVP:NoeudAsmRec=(
  Nom:'FDIVP';
  Code:caFDIVP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFDIVRP:NoeudAsmRec=(
  Nom:'FDIVRP';
  Code:caFDIVRP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFDIVR:NoeudAsmRec=(
  Nom:'FDIVR';
  Code:caFDIVR;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFDIVP);
  Droite:Ofs(acFDIVRP)
 );

 acFDIV:NoeudAsmRec=(
  Nom:'FDIV';
  Code:caFDIV;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFDECSTP);
  Droite:Ofs(acFDIVR)
 );

 acFEXTRACT:NoeudAsmRec=(
  Nom:'FEXTRACT';
  Code:caFEXTRACT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F4;
  Gauche:0;
  Droite:0
 );

 acFIADD:NoeudAsmRec=(
  Nom:'FIADD';
  Code:caFIADD;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFFREE:NoeudAsmRec=(
  Nom:'FFREE';
  Code:caFFREE;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFEXTRACT);
  Droite:Ofs(acFIADD)
 );

 acFICOMP:NoeudAsmRec=(
  Nom:'FICOMP';
  Code:caFICOMP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFIDIVR:NoeudAsmRec=(
  Nom:'FIDIVR';
  Code:caFIDIVR;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFIDIV:NoeudAsmRec=(
  Nom:'FIDIV';
  Code:caFIDIV;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFICOMP);
  Droite:Ofs(acFIDIVR)
 );

 acFICOM:NoeudAsmRec=(
  Nom:'FICOM';
  Code:caFICOM;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFFREE);
  Droite:Ofs(acFIDIV)
 );

 acFENI:NoeudAsmRec=(
  Nom:'FENI';
  Code:caFENI;
  CPU:p8087;
  Parameters:No;
  OpCode:#$9B#$DB#$E0;
  Gauche:Ofs(acFDIV);
  Droite:Ofs(acFICOM)
 );

 acFDECSTEP:NoeudAsmRec=(
  Nom:'FDECSTEP';
  Code:caFDECSTEP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F6;
  Gauche:Ofs(acFCMOVU);
  Droite:Ofs(acFENI)
 );

 acFCMOVB:NoeudAsmRec=(
  Nom:'FCMOVB';
  Code:caFCMOVB;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acDW);
  Droite:Ofs(acFDECSTEP)
 );

 acCMPXCHG486:NoeudAsmRec=(
  Nom:'CMPXCHG486';
  Code:caCMPXCHG486;
  CPU:p80486;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acCMOVC);
  Droite:Ofs(acFCMOVB)
 );

 acFIN:NoeudAsmRec=(
  Nom:'FIN';
  Code:caFIN;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFIMUL:NoeudAsmRec=(
  Nom:'FIMUL';
  Code:caFIMUL;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFIN)
 );

 acFINCSTP:NoeudAsmRec=(
  Nom:'FINCSTP';
  Code:caFINCSTP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F7;
  Gauche:0;
  Droite:0
 );

 acFISTP:NoeudAsmRec=(
  Nom:'FISTP';
  Code:caFISTP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFINIT:NoeudAsmRec=(
  Nom:'FINIT';
  Code:caFINIT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$9B#$DB#$E3;
  Gauche:Ofs(acFINCSTP);
  Droite:Ofs(acFISTP)
 );

 acFINCSTEP:NoeudAsmRec=(
  Nom:'FINCSTEP';
  Code:caFINCSTEP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F7;
  Gauche:Ofs(acFIMUL);
  Droite:Ofs(acFINIT)
 );

 acFLOAT:NoeudAsmRec=(
  Nom:'FLOAT';
  Code:caFLOAT;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFISUBR:NoeudAsmRec=(
  Nom:'FISUBR';
  Code:caFISUBR;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFLOAT)
 );

 acFLOATINIT:NoeudAsmRec=(
  Nom:'FLOATINIT';
  Code:caFLOATINIT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$9B#$DB#$E3;
  Gauche:0;
  Droite:0
 );

 acFLOATROUNDINTEGER:NoeudAsmRec=(
  Nom:'FLOATROUNDINTEGER';
  Code:caFLOATROUNDINTEGER;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FC;
  Gauche:0;
  Droite:0
 );

 acFLOATNOP:NoeudAsmRec=(
  Nom:'FLOATNOP';
  Code:caFLOATNOP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$D0;
  Gauche:Ofs(acFLOATINIT);
  Droite:Ofs(acFLOATROUNDINTEGER)
 );

 acFLOATABS:NoeudAsmRec=(
  Nom:'FLOATABS';
  Code:caFLOATABS;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E1;
  Gauche:Ofs(acFISUBR);
  Droite:Ofs(acFLOATNOP)
 );

 acFISUB:NoeudAsmRec=(
  Nom:'FISUB';
  Code:caFISUB;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFINCSTEP);
  Droite:Ofs(acFLOATABS)
 );

 acFLDCW:NoeudAsmRec=(
  Nom:'FLDCW';
  Code:caFLDCW;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFLD1:NoeudAsmRec=(
  Nom:'FLD1';
  Code:caFLD1;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E8;
  Gauche:0;
  Droite:Ofs(acFLDCW)
 );

 acFLDL2E:NoeudAsmRec=(
  Nom:'FLDL2E';
  Code:caFLDL2E;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$EA;
  Gauche:0;
  Droite:0
 );

 acFLDLG2:NoeudAsmRec=(
  Nom:'FLDLG2';
  Code:caFLDLG2;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$EC;
  Gauche:0;
  Droite:0
 );

 acFLDL2T:NoeudAsmRec=(
  Nom:'FLDL2T';
  Code:caFLDL2T;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E9;
  Gauche:Ofs(acFLDL2E);
  Droite:Ofs(acFLDLG2)
 );

 acFLDENV:NoeudAsmRec=(
  Nom:'FLDENV';
  Code:caFLDENV;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFLD1);
  Droite:Ofs(acFLDL2T)
 );

 acFLDZ:NoeudAsmRec=(
  Nom:'FLDZ';
  Code:caFLDZ;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$EE;
  Gauche:0;
  Droite:0
 );

 acFLDPI:NoeudAsmRec=(
  Nom:'FLDPI';
  Code:caFLDPI;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$EB;
  Gauche:0;
  Droite:Ofs(acFLDZ)
 );

 acFMULP:NoeudAsmRec=(
  Nom:'FMULP';
  Code:caFMULP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFNDISI:NoeudAsmRec=(
  Nom:'FNDISI';
  Code:caFNDISI;
  CPU:p8087;
  Parameters:No;
  OpCode:#$DB#$E1;
  Gauche:0;
  Droite:0
 );

 acFNCLEX:NoeudAsmRec=(
  Nom:'FNCLEX';
  Code:caFNCLEX;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$DB#$E2;
  Gauche:Ofs(acFMULP);
  Droite:Ofs(acFNDISI)
 );

 acFMUL:NoeudAsmRec=(
  Nom:'FMUL';
  Code:caFMUL;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFLDPI);
  Droite:Ofs(acFNCLEX)
 );

 acFLDLN2:NoeudAsmRec=(
  Nom:'FLDLN2';
  Code:caFLDLN2;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$ED;
  Gauche:Ofs(acFLDENV);
  Droite:Ofs(acFMUL)
 );

 acFLD:NoeudAsmRec=(
  Nom:'FLD';
  Code:caFLD;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFISUB);
  Droite:Ofs(acFLDLN2)
 );

 acFNOP:NoeudAsmRec=(
  Nom:'FNOP';
  Code:caFNOP;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$D0;
  Gauche:0;
  Droite:0
 );

 acFNINIT:NoeudAsmRec=(
  Nom:'FNINIT';
  Code:caFNINIT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$DB#$E3;
  Gauche:0;
  Droite:Ofs(acFNOP)
 );

 acFNSTENV:NoeudAsmRec=(
  Nom:'FNSTENV';
  Code:caFNSTENV;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFNSTSW:NoeudAsmRec=(
  Nom:'FNSTSW';
  Code:caFNSTSW;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFNSTCW:NoeudAsmRec=(
  Nom:'FNSTCW';
  Code:caFNSTCW;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFNSTENV);
  Droite:Ofs(acFNSTSW)
 );

 acFNSAVE:NoeudAsmRec=(
  Nom:'FNSAVE';
  Code:caFNSAVE;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFNINIT);
  Droite:Ofs(acFNSTCW)
 );

 acFPREM1:NoeudAsmRec=(
  Nom:'FPREM1';
  Code:caFPREM1;
  CPU:p80387Plus;
  Parameters:No;
  OpCode:#$D9#$F5;
  Gauche:0;
  Droite:0
 );

 acFPREM:NoeudAsmRec=(
  Nom:'FPREM';
  Code:caFPREM;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F8;
  Gauche:0;
  Droite:Ofs(acFPREM1)
 );

 acFROUNDINTEGER:NoeudAsmRec=(
  Nom:'FROUNDINTEGER';
  Code:caFROUNDINTEGER;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FC;
  Gauche:0;
  Droite:0
 );

 acFRSTOR:NoeudAsmRec=(
  Nom:'FRSTOR';
  Code:caFRSTOR;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFRNDINT:NoeudAsmRec=(
  Nom:'FRNDINT';
  Code:caFRNDINT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FC;
  Gauche:Ofs(acFROUNDINTEGER);
  Droite:Ofs(acFRSTOR)
 );

 acFPTAN:NoeudAsmRec=(
  Nom:'FPTAN';
  Code:caFPTAN;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F2;
  Gauche:Ofs(acFPREM);
  Droite:Ofs(acFRNDINT)
 );

 acFPATAN:NoeudAsmRec=(
  Nom:'FPATAN';
  Code:caFPATAN;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F3;
  Gauche:Ofs(acFNSAVE);
  Droite:Ofs(acFPTAN)
 );

 acFSCALE:NoeudAsmRec=(
  Nom:'FSCALE';
  Code:caFSCALE;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FD;
  Gauche:0;
  Droite:0
 );

 acFSAVE:NoeudAsmRec=(
  Nom:'FSAVE';
  Code:caFSAVE;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acFSCALE)
 );

 acFSIN:NoeudAsmRec=(
  Nom:'FSIN';
  Code:caFSIN;
  CPU:p80387Plus;
  Parameters:No;
  OpCode:#$D9#$FE;
  Gauche:0;
  Droite:0
 );

 acFSQRT:NoeudAsmRec=(
  Nom:'FSQRT';
  Code:caFSQRT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$FA;
  Gauche:0;
  Droite:0
 );

 acFSINCOS:NoeudAsmRec=(
  Nom:'FSINCOS';
  Code:caFSINCOS;
  CPU:p80387Plus;
  Parameters:No;
  OpCode:#$D9#$FB;
  Gauche:Ofs(acFSIN);
  Droite:Ofs(acFSQRT)
 );

 acFSETPM:NoeudAsmRec=(
  Nom:'FSETPM';
  Code:caFSETPM;
  CPU:p80387Plus;
  Parameters:No;
  OpCode:#$DB#$E4;
  Gauche:Ofs(acFSAVE);
  Droite:Ofs(acFSINCOS)
 );

 acFSTCW:NoeudAsmRec=(
  Nom:'FSTCW';
  Code:caFSTCW;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFSTP:NoeudAsmRec=(
  Nom:'FSTP';
  Code:caFSTP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFSTENV:NoeudAsmRec=(
  Nom:'FSTENV';
  Code:caFSTENV;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFSTCW);
  Droite:Ofs(acFSTP)
 );

 acFSUB:NoeudAsmRec=(
  Nom:'FSUB';
  Code:caFSUB;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFSUBR:NoeudAsmRec=(
  Nom:'FSUBR';
  Code:caFSUBR;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFSUBPP:NoeudAsmRec=(
  Nom:'FSUBPP';
  Code:caFSUBPP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFSUB);
  Droite:Ofs(acFSUBR)
 );

 acFSTSW:NoeudAsmRec=(
  Nom:'FSTSW';
  Code:caFSTSW;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFSTENV);
  Droite:Ofs(acFSUBPP)
 );

 acFST:NoeudAsmRec=(
  Nom:'FST';
  Code:caFST;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFSETPM);
  Droite:Ofs(acFSTSW)
 );

 acFS:NoeudAsmRec=(
  Nom:'FS';
  Code:caFS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$64;
  Gauche:Ofs(acFPATAN);
  Droite:Ofs(acFST)
 );

 acFNENI:NoeudAsmRec=(
  Nom:'FNENI';
  Code:caFNENI;
  CPU:p8087;
  Parameters:No;
  OpCode:#$DB#$E0;
  Gauche:Ofs(acFLD);
  Droite:Ofs(acFS)
 );

 acFUCOM:NoeudAsmRec=(
  Nom:'FUCOM';
  Code:caFUCOM;
  CPU:p80387Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFTST:NoeudAsmRec=(
  Nom:'FTST';
  Code:caFTST;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E4;
  Gauche:0;
  Droite:Ofs(acFUCOM)
 );

 acFUCOMIP:NoeudAsmRec=(
  Nom:'FUCOMIP';
  Code:caFUCOMIP;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acFUCOMPP:NoeudAsmRec=(
  Nom:'FUCOMPP';
  Code:caFUCOMPP;
  CPU:p80387Plus;
  Parameters:No;
  OpCode:#$DA#$E9;
  Gauche:0;
  Droite:0
 );

 acFUCOMP:NoeudAsmRec=(
  Nom:'FUCOMP';
  Code:caFUCOMP;
  CPU:p80387Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFUCOMIP);
  Droite:Ofs(acFUCOMPP)
 );

 acFUCOMI:NoeudAsmRec=(
  Nom:'FUCOMI';
  Code:caFUCOMI;
  CPU:p80686Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFTST);
  Droite:Ofs(acFUCOMP)
 );

 acFXCH:NoeudAsmRec=(
  Nom:'FXCH';
  Code:caFXCH;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:#$D9#$C9;
  Gauche:0;
  Droite:0
 );

 acFXAM:NoeudAsmRec=(
  Nom:'FXAM';
  Code:caFXAM;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$E5;
  Gauche:0;
  Droite:Ofs(acFXCH)
 );

 acFYL2X:NoeudAsmRec=(
  Nom:'FYL2X';
  Code:caFYL2X;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F1;
  Gauche:0;
  Droite:0
 );

 acGS:NoeudAsmRec=(
  Nom:'GS';
  Code:caGS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$65;
  Gauche:0;
  Droite:0
 );

 acFYL2XP1:NoeudAsmRec=(
  Nom:'FYL2XP1';
  Code:caFYL2XP1;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F9;
  Gauche:Ofs(acFYL2X);
  Droite:Ofs(acGS)
 );

 acFXTRACT:NoeudAsmRec=(
  Nom:'FXTRACT';
  Code:caFXTRACT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:#$D9#$F4;
  Gauche:Ofs(acFXAM);
  Droite:Ofs(acFYL2XP1)
 );

 acFWAIT:NoeudAsmRec=(
  Nom:'FWAIT';
  Code:caFWAIT;
  CPU:p8087Plus;
  Parameters:No;
  OpCode:'';
  Gauche:Ofs(acFUCOMI);
  Droite:Ofs(acFXTRACT)
 );

 acIBTS:NoeudAsmRec=(
  Nom:'IBTS';
  Code:caIBTS;
  CPU:p80386;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acHLT:NoeudAsmRec=(
  Nom:'HLT';
  Code:caHLT;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F4;
  Gauche:0;
  Droite:Ofs(acIBTS)
 );

 acIDIV:NoeudAsmRec=(
  Nom:'IDIV';
  Code:caIDIV;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F8;
  Gauche:0;
  Droite:0
 );

 acIMUL:NoeudAsmRec=(
  Nom:'IMUL';
  Code:caIMUL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E8;
  Gauche:0;
  Droite:0
 );

 acIF:NoeudAsmRec=(
  Nom:'IF';
  Code:caIF;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acIDIV);
  Droite:Ofs(acIMUL)
 );

 acICEBP:NoeudAsmRec=(
  Nom:'ICEBP';
  Code:caICEBP;
  CPU:p80686Plus;
  Parameters:No;
  OpCode:#$F1;
  Gauche:Ofs(acHLT);
  Droite:Ofs(acIF)
 );

 acINSB:NoeudAsmRec=(
  Nom:'INSB';
  Code:caINSB;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$6C;
  Gauche:0;
  Droite:0
 );

 acINC:NoeudAsmRec=(
  Nom:'INC';
  Code:caINC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acINSB)
 );

 acINSW:NoeudAsmRec=(
  Nom:'INSW';
  Code:caINSW;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$6D;
  Gauche:0;
  Droite:0
 );

 acINT01:NoeudAsmRec=(
  Nom:'INT01';
  Code:caINT01;
  CPU:p80686Plus;
  Parameters:No;
  OpCode:#$F1;
  Gauche:0;
  Droite:0
 );

 acINT:NoeudAsmRec=(
  Nom:'INT';
  Code:caINT;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$CD;
  Gauche:Ofs(acINSW);
  Droite:Ofs(acINT01)
 );

 acINSD:NoeudAsmRec=(
  Nom:'INSD';
  Code:caINSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$6D;
  Gauche:Ofs(acINC);
  Droite:Ofs(acINT)
 );

 acIN:NoeudAsmRec=(
  Nom:'IN';
  Code:caIN;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acICEBP);
  Droite:Ofs(acINSD)
 );

 acHALT:NoeudAsmRec=(
  Nom:'HALT';
  Code:caHALT;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F4;
  Gauche:Ofs(acFWAIT);
  Droite:Ofs(acIN)
 );

 acINTERRUPT:NoeudAsmRec=(
  Nom:'INTERRUPT';
  Code:caINTERRUPT;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$CD;
  Gauche:0;
  Droite:0
 );

 acINT3:NoeudAsmRec=(
  Nom:'INT3';
  Code:caINT3;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$CC;
  Gauche:0;
  Droite:Ofs(acINTERRUPT)
 );

 acINTO:NoeudAsmRec=(
  Nom:'INTO';
  Code:caINTO;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$CE;
  Gauche:0;
  Droite:0
 );

 acINVLPG:NoeudAsmRec=(
  Nom:'INVLPG';
  Code:caINVLPG;
  CPU:p80486Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acINVD:NoeudAsmRec=(
  Nom:'INVD';
  Code:caINVD;
  CPU:p80486Plus;
  Parameters:No;
  OpCode:#$0F#$08;
  Gauche:Ofs(acINTO);
  Droite:Ofs(acINVLPG)
 );

 acINTERRUPTRETURN:NoeudAsmRec=(
  Nom:'INTERRUPTRETURN';
  Code:caINTERRUPTRETURN;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$CF;
  Gauche:Ofs(acINT3);
  Droite:Ofs(acINVD)
 );

 acIRETW:NoeudAsmRec=(
  Nom:'IRETW';
  Code:caIRETW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$CF;
  Gauche:0;
  Droite:0
 );

 acIRETD:NoeudAsmRec=(
  Nom:'IRETD';
  Code:caIRETD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$CF;
  Gauche:0;
  Droite:Ofs(acIRETW)
 );

 acJAE:NoeudAsmRec=(
  Nom:'JAE';
  Code:caJAE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$73;
  Gauche:0;
  Droite:0
 );

 acJBE:NoeudAsmRec=(
  Nom:'JBE';
  Code:caJBE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$76;
  Gauche:0;
  Droite:0
 );

 acJB:NoeudAsmRec=(
  Nom:'JB';
  Code:caJB;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$72;
  Gauche:Ofs(acJAE);
  Droite:Ofs(acJBE)
 );

 acJA:NoeudAsmRec=(
  Nom:'JA';
  Code:caJA;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$77;
  Gauche:Ofs(acIRETD);
  Droite:Ofs(acJB)
 );

 acIRET:NoeudAsmRec=(
  Nom:'IRET';
  Code:caIRET;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$CF;
  Gauche:Ofs(acINTERRUPTRETURN);
  Droite:Ofs(acJA)
 );

 acJE:NoeudAsmRec=(
  Nom:'JE';
  Code:caJE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$74;
  Gauche:0;
  Droite:0
 );

 acJCXZ:NoeudAsmRec=(
  Nom:'JCXZ';
  Code:caJCXZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E3;
  Gauche:0;
  Droite:Ofs(acJE)
 );

 acJG:NoeudAsmRec=(
  Nom:'JG';
  Code:caJG;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7F;
  Gauche:0;
  Droite:0
 );

 acJL:NoeudAsmRec=(
  Nom:'JL';
  Code:caJL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7C;
  Gauche:0;
  Droite:0
 );

 acJGE:NoeudAsmRec=(
  Nom:'JGE';
  Code:caJGE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7D;
  Gauche:Ofs(acJG);
  Droite:Ofs(acJL)
 );

 acJECXZ:NoeudAsmRec=(
  Nom:'JECXZ';
  Code:caJECXZ;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$66#$E3;
  Gauche:Ofs(acJCXZ);
  Droite:Ofs(acJGE)
 );

 acJMP:NoeudAsmRec=(
  Nom:'JMP';
  Code:caJMP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$EB;
  Gauche:0;
  Droite:0
 );

 acJNAE:NoeudAsmRec=(
  Nom:'JNAE';
  Code:caJNAE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$72;
  Gauche:0;
  Droite:0
 );

 acJNA:NoeudAsmRec=(
  Nom:'JNA';
  Code:caJNA;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$76;
  Gauche:Ofs(acJMP);
  Droite:Ofs(acJNAE)
 );

 acJNC:NoeudAsmRec=(
  Nom:'JNC';
  Code:caJNC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$72;
  Gauche:0;
  Droite:0
 );

 acJNG:NoeudAsmRec=(
  Nom:'JNG';
  Code:caJNG;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7E;
  Gauche:0;
  Droite:0
 );

 acJNE:NoeudAsmRec=(
  Nom:'JNE';
  Code:caJNE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$75;
  Gauche:Ofs(acJNC);
  Droite:Ofs(acJNG)
 );

 acJNB:NoeudAsmRec=(
  Nom:'JNB';
  Code:caJNB;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$73;
  Gauche:Ofs(acJNA);
  Droite:Ofs(acJNE)
 );

 acJLE:NoeudAsmRec=(
  Nom:'JLE';
  Code:caJLE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7E;
  Gauche:Ofs(acJECXZ);
  Droite:Ofs(acJNB)
 );

 acJC:NoeudAsmRec=(
  Nom:'JC';
  Code:caJC;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$72;
  Gauche:Ofs(acIRET);
  Droite:Ofs(acJLE)
 );

 acINT1:NoeudAsmRec=(
  Nom:'INT1';
  Code:caINT1;
  CPU:p80686Plus;
  Parameters:No;
  OpCode:#$F1;
  Gauche:Ofs(acHALT);
  Droite:Ofs(acJC)
 );

 acFSUBRP:NoeudAsmRec=(
  Nom:'FSUBRP';
  Code:caFSUBRP;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acFNENI);
  Droite:Ofs(acINT1)
 );

 acFILD:NoeudAsmRec=(
  Nom:'FILD';
  Code:caFILD;
  CPU:p8087Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acCMPXCHG486);
  Droite:Ofs(acFSUBRP)
 );

 acJNLE:NoeudAsmRec=(
  Nom:'JNLE';
  Code:caJNLE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7F;
  Gauche:0;
  Droite:0
 );

 acJNL:NoeudAsmRec=(
  Nom:'JNL';
  Code:caJNL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7D;
  Gauche:0;
  Droite:Ofs(acJNLE)
 );

 acJNP:NoeudAsmRec=(
  Nom:'JNP';
  Code:caJNP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7B;
  Gauche:0;
  Droite:0
 );

 acJNZ:NoeudAsmRec=(
  Nom:'JNZ';
  Code:caJNZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$75;
  Gauche:0;
  Droite:0
 );

 acJNS:NoeudAsmRec=(
  Nom:'JNS';
  Code:caJNS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$79;
  Gauche:Ofs(acJNP);
  Droite:Ofs(acJNZ)
 );

 acJNO:NoeudAsmRec=(
  Nom:'JNO';
  Code:caJNO;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$71;
  Gauche:Ofs(acJNL);
  Droite:Ofs(acJNS)
 );

 acJPE:NoeudAsmRec=(
  Nom:'JPE';
  Code:caJPE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7A;
  Gauche:0;
  Droite:0
 );

 acJP:NoeudAsmRec=(
  Nom:'JP';
  Code:caJP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7A;
  Gauche:0;
  Droite:Ofs(acJPE)
 );

 acJS:NoeudAsmRec=(
  Nom:'JS';
  Code:caJS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$78;
  Gauche:0;
  Droite:0
 );

 acLAHF:NoeudAsmRec=(
  Nom:'LAHF';
  Code:caLAHF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9F;
  Gauche:0;
  Droite:0
 );

 acJZ:NoeudAsmRec=(
  Nom:'JZ';
  Code:caJZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$74;
  Gauche:Ofs(acJS);
  Droite:Ofs(acLAHF)
 );

 acJPO:NoeudAsmRec=(
  Nom:'JPO';
  Code:caJPO;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7B;
  Gauche:Ofs(acJP);
  Droite:Ofs(acJZ)
 );

 acJO:NoeudAsmRec=(
  Nom:'JO';
  Code:caJO;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$70;
  Gauche:Ofs(acJNO);
  Droite:Ofs(acJPO)
 );

 acLEA:NoeudAsmRec=(
  Nom:'LEA';
  Code:caLEA;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$8D;
  Gauche:0;
  Droite:0
 );

 acLDS:NoeudAsmRec=(
  Nom:'LDS';
  Code:caLDS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$C5;
  Gauche:0;
  Droite:Ofs(acLEA)
 );

 acLES:NoeudAsmRec=(
  Nom:'LES';
  Code:caLES;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$C4;
  Gauche:0;
  Droite:0
 );

 acLGDT:NoeudAsmRec=(
  Nom:'LGDT';
  Code:caLGDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acLFS:NoeudAsmRec=(
  Nom:'LFS';
  Code:caLFS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$B4;
  Gauche:Ofs(acLES);
  Droite:Ofs(acLGDT)
 );

 acLEAVE:NoeudAsmRec=(
  Nom:'LEAVE';
  Code:caLEAVE;
  CPU:p80186Plus;
  Parameters:No;
  OpCode:#$C9;
  Gauche:Ofs(acLDS);
  Droite:Ofs(acLFS)
 );

 acLLDT:NoeudAsmRec=(
  Nom:'LLDT';
  Code:caLLDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acLIDT:NoeudAsmRec=(
  Nom:'LIDT';
  Code:caLIDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acLLDT)
 );

 acLOADAHFLAGS:NoeudAsmRec=(
  Nom:'LOADAHFLAGS';
  Code:caLOADAHFLAGS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9F;
  Gauche:0;
  Droite:0
 );

 acLOADALL286:NoeudAsmRec=(
  Nom:'LOADALL286';
  Code:caLOADALL286;
  CPU:p80286;
  Parameters:No;
  OpCode:#$0F#$05;
  Gauche:0;
  Droite:0
 );

 acLOADALL:NoeudAsmRec=(
  Nom:'LOADALL';
  Code:caLOADALL;
  CPU:p80386;
  Parameters:No;
  OpCode:#$0F#$07;
  Gauche:Ofs(acLOADAHFLAGS);
  Droite:Ofs(acLOADALL286)
 );

 acLMSW:NoeudAsmRec=(
  Nom:'LMSW';
  Code:caLMSW;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acLIDT);
  Droite:Ofs(acLOADALL)
 );

 acLGS:NoeudAsmRec=(
  Nom:'LGS';
  Code:caLGS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$B5;
  Gauche:Ofs(acLEAVE);
  Droite:Ofs(acLMSW)
 );

 acLAR:NoeudAsmRec=(
  Nom:'LAR';
  Code:caLAR;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acJO);
  Droite:Ofs(acLGS)
 );

 acLOADSTRBYTE:NoeudAsmRec=(
  Nom:'LOADSTRBYTE';
  Code:caLOADSTRBYTE;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AC;
  Gauche:0;
  Droite:0
 );

 acLOADSD:NoeudAsmRec=(
  Nom:'LOADSD';
  Code:caLOADSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$AD;
  Gauche:0;
  Droite:Ofs(acLOADSTRBYTE)
 );

 acLOADSTRWORD:NoeudAsmRec=(
  Nom:'LOADSTRWORD';
  Code:caLOADSTRWORD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AD;
  Gauche:0;
  Droite:0
 );

 acLOCK:NoeudAsmRec=(
  Nom:'LOCK';
  Code:caLOCK;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F0;
  Gauche:0;
  Droite:0
 );

 acLOADSW:NoeudAsmRec=(
  Nom:'LOADSW';
  Code:caLOADSW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AD;
  Gauche:Ofs(acLOADSTRWORD);
  Droite:Ofs(acLOCK)
 );

 acLOADSTRDOUBLEWORD:NoeudAsmRec=(
  Nom:'LOADSTRDOUBLEWORD';
  Code:caLOADSTRDOUBLEWORD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$AD;
  Gauche:Ofs(acLOADSD);
  Droite:Ofs(acLOADSW)
 );

 acLODSW:NoeudAsmRec=(
  Nom:'LODSW';
  Code:caLODSW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AD;
  Gauche:0;
  Droite:0
 );

 acLODSD:NoeudAsmRec=(
  Nom:'LODSD';
  Code:caLODSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$AD;
  Gauche:0;
  Droite:Ofs(acLODSW)
 );

 acLOOPE:NoeudAsmRec=(
  Nom:'LOOPE';
  Code:caLOOPE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E1;
  Gauche:0;
  Droite:0
 );

 acLOOPNZ:NoeudAsmRec=(
  Nom:'LOOPNZ';
  Code:caLOOPNZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E0;
  Gauche:0;
  Droite:0
 );

 acLOOPNE:NoeudAsmRec=(
  Nom:'LOOPNE';
  Code:caLOOPNE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E0;
  Gauche:Ofs(acLOOPE);
  Droite:Ofs(acLOOPNZ)
 );

 acLOOP:NoeudAsmRec=(
  Nom:'LOOP';
  Code:caLOOP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E2;
  Gauche:Ofs(acLODSD);
  Droite:Ofs(acLOOPNE)
 );

 acLODSB:NoeudAsmRec=(
  Nom:'LODSB';
  Code:caLODSB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AC;
  Gauche:Ofs(acLOADSTRDOUBLEWORD);
  Droite:Ofs(acLOOP)
 );

 acLSS:NoeudAsmRec=(
  Nom:'LSS';
  Code:caLSS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$B2;
  Gauche:0;
  Droite:0
 );

 acLSL:NoeudAsmRec=(
  Nom:'LSL';
  Code:caLSL;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acLSS)
 );

 acMOV:NoeudAsmRec=(
  Nom:'MOV';
  Code:caMOV;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acMOVQ:NoeudAsmRec=(
  Nom:'MOVQ';
  Code:caMOVQ;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acMOVD:NoeudAsmRec=(
  Nom:'MOVD';
  Code:caMOVD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acMOV);
  Droite:Ofs(acMOVQ)
 );

 acLTR:NoeudAsmRec=(
  Nom:'LTR';
  Code:caLTR;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acLSL);
  Droite:Ofs(acMOVD)
 );

 acMOVSD:NoeudAsmRec=(
  Nom:'MOVSD';
  Code:caMOVSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$A5;
  Gauche:0;
  Droite:0
 );

 acMOVSX:NoeudAsmRec=(
  Nom:'MOVSX';
  Code:caMOVSX;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acMOVSW:NoeudAsmRec=(
  Nom:'MOVSW';
  Code:caMOVSW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$A5;
  Gauche:Ofs(acMOVSD);
  Droite:Ofs(acMOVSX)
 );

 acMUL:NoeudAsmRec=(
  Nom:'MUL';
  Code:caMUL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E0;
  Gauche:0;
  Droite:0
 );

 acNOP:NoeudAsmRec=(
  Nom:'NOP';
  Code:caNOP;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$90;
  Gauche:0;
  Droite:0
 );

 acNEG:NoeudAsmRec=(
  Nom:'NEG';
  Code:caNEG;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$D8;
  Gauche:Ofs(acMUL);
  Droite:Ofs(acNOP)
 );

 acMOVZX:NoeudAsmRec=(
  Nom:'MOVZX';
  Code:caMOVZX;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acMOVSW);
  Droite:Ofs(acNEG)
 );

 acMOVSB:NoeudAsmRec=(
  Nom:'MOVSB';
  Code:caMOVSB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$A4;
  Gauche:Ofs(acLTR);
  Droite:Ofs(acMOVZX)
 );

 acLOOPZ:NoeudAsmRec=(
  Nom:'LOOPZ';
  Code:caLOOPZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$E1;
  Gauche:Ofs(acLODSB);
  Droite:Ofs(acMOVSB)
 );

 acLOADSB:NoeudAsmRec=(
  Nom:'LOADSB';
  Code:caLOADSB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AC;
  Gauche:Ofs(acLAR);
  Droite:Ofs(acLOOPZ)
 );

 acOR:NoeudAsmRec=(
  Nom:'OR';
  Code:caOR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$08;
  Gauche:0;
  Droite:0
 );

 acNOT:NoeudAsmRec=(
  Nom:'NOT';
  Code:caNOT;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$D0;
  Gauche:0;
  Droite:Ofs(acOR)
 );

 acOUTSB:NoeudAsmRec=(
  Nom:'OUTSB';
  Code:caOUTSB;
  CPU:p80186Plus;
  Parameters:No;
  OpCode:#$6E;
  Gauche:0;
  Droite:0
 );

 acOUTSW:NoeudAsmRec=(
  Nom:'OUTSW';
  Code:caOUTSW;
  CPU:p80186Plus;
  Parameters:No;
  OpCode:#$6F;
  Gauche:0;
  Droite:0
 );

 acOUTSD:NoeudAsmRec=(
  Nom:'OUTSD';
  Code:caOUTSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$6F;
  Gauche:Ofs(acOUTSB);
  Droite:Ofs(acOUTSW)
 );

 acOUT:NoeudAsmRec=(
  Nom:'OUT';
  Code:caOUT;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acNOT);
  Droite:Ofs(acOUTSD)
 );

 acPACKUSWB:NoeudAsmRec=(
  Nom:'PACKUSWB';
  Code:caPACKUSWB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPACKSSWB:NoeudAsmRec=(
  Nom:'PACKSSWB';
  Code:caPACKSSWB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPACKUSWB)
 );

 acPADDD:NoeudAsmRec=(
  Nom:'PADDD';
  Code:caPADDD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPADDSW:NoeudAsmRec=(
  Nom:'PADDSW';
  Code:caPADDSW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPADDSB:NoeudAsmRec=(
  Nom:'PADDSB';
  Code:caPADDSB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPADDD);
  Droite:Ofs(acPADDSW)
 );

 acPADDB:NoeudAsmRec=(
  Nom:'PADDB';
  Code:caPADDB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPACKSSWB);
  Droite:Ofs(acPADDSB)
 );

 acPACKSSDW:NoeudAsmRec=(
  Nom:'PACKSSDW';
  Code:caPACKSSDW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acOUT);
  Droite:Ofs(acPADDB)
 );

 acPADDW:NoeudAsmRec=(
  Nom:'PADDW';
  Code:caPADDW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPADDUSW:NoeudAsmRec=(
  Nom:'PADDUSW';
  Code:caPADDUSW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPADDW)
 );

 acPANDN:NoeudAsmRec=(
  Nom:'PANDN';
  Code:caPANDN;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPAVEB:NoeudAsmRec=(
  Nom:'PAVEB';
  Code:caPAVEB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPADDSIW:NoeudAsmRec=(
  Nom:'PADDSIW';
  Code:caPADDSIW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPANDN);
  Droite:Ofs(acPAVEB)
 );

 acPAND:NoeudAsmRec=(
  Nom:'PAND';
  Code:caPAND;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPADDUSW);
  Droite:Ofs(acPADDSIW)
 );

 acPCMPEQW:NoeudAsmRec=(
  Nom:'PCMPEQW';
  Code:caPCMPEQW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPCMPEQD:NoeudAsmRec=(
  Nom:'PCMPEQD';
  Code:caPCMPEQD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPCMPEQW)
 );

 acPCMPGTD:NoeudAsmRec=(
  Nom:'PCMPGTD';
  Code:caPCMPGTD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPDISTIB:NoeudAsmRec=(
  Nom:'PDISTIB';
  Code:caPDISTIB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPCMPGTW:NoeudAsmRec=(
  Nom:'PCMPGTW';
  Code:caPCMPGTW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPCMPGTD);
  Droite:Ofs(acPDISTIB)
 );

 acPCMPGTB:NoeudAsmRec=(
  Nom:'PCMPGTB';
  Code:caPCMPGTB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPCMPEQD);
  Droite:Ofs(acPCMPGTW)
 );

 acPCMPEQB:NoeudAsmRec=(
  Nom:'PCMPEQB';
  Code:caPCMPEQB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPAND);
  Droite:Ofs(acPCMPGTB)
 );

 acPADDUSB:NoeudAsmRec=(
  Nom:'PADDUSB';
  Code:caPADDUSB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPACKSSDW);
  Droite:Ofs(acPCMPEQB)
 );

 acPMAGW:NoeudAsmRec=(
  Nom:'PMAGW';
  Code:caPMAGW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPMADDWD:NoeudAsmRec=(
  Nom:'PMADDWD';
  Code:caPMADDWD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPMAGW)
 );

 acPMULHRIW:NoeudAsmRec=(
  Nom:'PMULHRIW';
  Code:caPMULHRIW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPMVZB:NoeudAsmRec=(
  Nom:'PMVZB';
  Code:caPMVZB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPMULHW:NoeudAsmRec=(
  Nom:'PMULHW';
  Code:caPMULHW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPMULHRIW);
  Droite:Ofs(acPMVZB)
 );

 acPMULHRW:NoeudAsmRec=(
  Nom:'PMULHRW';
  Code:caPMULHRW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPMADDWD);
  Droite:Ofs(acPMULHW)
 );

 acPMVGEZB:NoeudAsmRec=(
  Nom:'PMVGEZB';
  Code:caPMVGEZB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPMVLZB:NoeudAsmRec=(
  Nom:'PMVLZB';
  Code:caPMVLZB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPMVGEZB)
 );

 acPOPA:NoeudAsmRec=(
  Nom:'POPA';
  Code:caPOPA;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$61;
  Gauche:0;
  Droite:0
 );

 acPOPALL:NoeudAsmRec=(
  Nom:'POPALL';
  Code:caPOPALL;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$61;
  Gauche:0;
  Droite:0
 );

 acPOPAD:NoeudAsmRec=(
  Nom:'POPAD';
  Code:caPOPAD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$61;
  Gauche:Ofs(acPOPA);
  Droite:Ofs(acPOPALL)
 );

 acPOP:NoeudAsmRec=(
  Nom:'POP';
  Code:caPOP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPMVLZB);
  Droite:Ofs(acPOPAD)
 );

 acPMVNZB:NoeudAsmRec=(
  Nom:'PMVNZB';
  Code:caPMVNZB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPMULHRW);
  Droite:Ofs(acPOP)
 );

 acPOPFD:NoeudAsmRec=(
  Nom:'POPFD';
  Code:caPOPFD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$9D;
  Gauche:0;
  Droite:0
 );

 acPOPF:NoeudAsmRec=(
  Nom:'POPF';
  Code:caPOPF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9D;
  Gauche:0;
  Droite:Ofs(acPOPFD)
 );

 acPOPFW:NoeudAsmRec=(
  Nom:'POPFW';
  Code:caPOPFW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9D;
  Gauche:0;
  Droite:0
 );

 acPSLLD:NoeudAsmRec=(
  Nom:'PSLLD';
  Code:caPSLLD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPOR:NoeudAsmRec=(
  Nom:'POR';
  Code:caPOR;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPOPFW);
  Droite:Ofs(acPSLLD)
 );

 acPOPFLAGS:NoeudAsmRec=(
  Nom:'POPFLAGS';
  Code:caPOPFLAGS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9D;
  Gauche:Ofs(acPOPF);
  Droite:Ofs(acPOR)
 );

 acPSLLW:NoeudAsmRec=(
  Nom:'PSLLW';
  Code:caPSLLW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSRAW:NoeudAsmRec=(
  Nom:'PSRAW';
  Code:caPSRAW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSRAD:NoeudAsmRec=(
  Nom:'PSRAD';
  Code:caPSRAD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSLLW);
  Droite:Ofs(acPSRAW)
 );

 acPSRLQ:NoeudAsmRec=(
  Nom:'PSRLQ';
  Code:caPSRLQ;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSUBB:NoeudAsmRec=(
  Nom:'PSUBB';
  Code:caPSUBB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSRLW:NoeudAsmRec=(
  Nom:'PSRLW';
  Code:caPSRLW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSRLQ);
  Droite:Ofs(acPSUBB)
 );

 acPSRLD:NoeudAsmRec=(
  Nom:'PSRLD';
  Code:caPSRLD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSRAD);
  Droite:Ofs(acPSRLW)
 );

 acPSLLQ:NoeudAsmRec=(
  Nom:'PSLLQ';
  Code:caPSLLQ;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPOPFLAGS);
  Droite:Ofs(acPSRLD)
 );

 acPOPAW:NoeudAsmRec=(
  Nom:'POPAW';
  Code:caPOPAW;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$61;
  Gauche:Ofs(acPMVNZB);
  Droite:Ofs(acPSLLQ)
 );

 acPMACHRIW:NoeudAsmRec=(
  Nom:'PMACHRIW';
  Code:caPMACHRIW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPADDUSB);
  Droite:Ofs(acPOPAW)
 );

 acNOP386:NoeudAsmRec=(
  Nom:'NOP386';
  Code:caNOP386;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$90;
  Gauche:Ofs(acLOADSB);
  Droite:Ofs(acPMACHRIW)
 );

 acPSUBSIW:NoeudAsmRec=(
  Nom:'PSUBSIW';
  Code:caPSUBSIW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSUBSB:NoeudAsmRec=(
  Nom:'PSUBSB';
  Code:caPSUBSB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPSUBSIW)
 );

 acPSUBUSB:NoeudAsmRec=(
  Nom:'PSUBUSB';
  Code:caPSUBUSB;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSUBW:NoeudAsmRec=(
  Nom:'PSUBW';
  Code:caPSUBW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPSUBUSW:NoeudAsmRec=(
  Nom:'PSUBUSW';
  Code:caPSUBUSW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSUBUSB);
  Droite:Ofs(acPSUBW)
 );

 acPSUBSW:NoeudAsmRec=(
  Nom:'PSUBSW';
  Code:caPSUBSW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSUBSB);
  Droite:Ofs(acPSUBUSW)
 );

 acPUNPCKHDQ:NoeudAsmRec=(
  Nom:'PUNPCKHDQ';
  Code:caPUNPCKHDQ;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPUNPCKHWD:NoeudAsmRec=(
  Nom:'PUNPCKHWD';
  Code:caPUNPCKHWD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acPUNPCKHDQ)
 );

 acPUNPCKLWD:NoeudAsmRec=(
  Nom:'PUNPCKLWD';
  Code:caPUNPCKLWD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPUSH:NoeudAsmRec=(
  Nom:'PUSH';
  Code:caPUSH;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPUNPCKLDQ:NoeudAsmRec=(
  Nom:'PUNPCKLDQ';
  Code:caPUNPCKLDQ;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPUNPCKLWD);
  Droite:Ofs(acPUSH)
 );

 acPUNPCKLBW:NoeudAsmRec=(
  Nom:'PUNPCKLBW';
  Code:caPUNPCKLBW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPUNPCKHWD);
  Droite:Ofs(acPUNPCKLDQ)
 );

 acPUNPCKHBW:NoeudAsmRec=(
  Nom:'PUNPCKHBW';
  Code:caPUNPCKHBW;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPSUBSW);
  Droite:Ofs(acPUNPCKLBW)
 );

 acPUSHALL:NoeudAsmRec=(
  Nom:'PUSHALL';
  Code:caPUSHALL;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$60;
  Gauche:0;
  Droite:0
 );

 acPUSHAD:NoeudAsmRec=(
  Nom:'PUSHAD';
  Code:caPUSHAD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$60;
  Gauche:0;
  Droite:Ofs(acPUSHALL)
 );

 acPUSHF:NoeudAsmRec=(
  Nom:'PUSHF';
  Code:caPUSHF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9C;
  Gauche:0;
  Droite:0
 );

 acPUSHFLAGS:NoeudAsmRec=(
  Nom:'PUSHFLAGS';
  Code:caPUSHFLAGS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9C;
  Gauche:0;
  Droite:0
 );

 acPUSHFD:NoeudAsmRec=(
  Nom:'PUSHFD';
  Code:caPUSHFD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$9C;
  Gauche:Ofs(acPUSHF);
  Droite:Ofs(acPUSHFLAGS)
 );

 acPUSHAW:NoeudAsmRec=(
  Nom:'PUSHAW';
  Code:caPUSHAW;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$60;
  Gauche:Ofs(acPUSHAD);
  Droite:Ofs(acPUSHFD)
 );

 acRCL:NoeudAsmRec=(
  Nom:'RCL';
  Code:caRCL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acPXOR:NoeudAsmRec=(
  Nom:'PXOR';
  Code:caPXOR;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acRCL)
 );

 acRDMSR:NoeudAsmRec=(
  Nom:'RDMSR';
  Code:caRDMSR;
  CPU:p80586Plus;
  Parameters:No;
  OpCode:#$0F#$32;
  Gauche:0;
  Droite:0
 );

 acRDTSC:NoeudAsmRec=(
  Nom:'RDTSC';
  Code:caRDTSC;
  CPU:p80586Plus;
  Parameters:No;
  OpCode:#$0F#$31;
  Gauche:0;
  Droite:0
 );

 acRDPMC:NoeudAsmRec=(
  Nom:'RDPMC';
  Code:caRDPMC;
  CPU:p80686Plus;
  Parameters:No;
  OpCode:#$0F#$33;
  Gauche:Ofs(acRDMSR);
  Droite:Ofs(acRDTSC)
 );

 acRCR:NoeudAsmRec=(
  Nom:'RCR';
  Code:caRCR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acPXOR);
  Droite:Ofs(acRDPMC)
 );

 acPUSHFW:NoeudAsmRec=(
  Nom:'PUSHFW';
  Code:caPUSHFW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9C;
  Gauche:Ofs(acPUSHAW);
  Droite:Ofs(acRCR)
 );

 acPUSHA:NoeudAsmRec=(
  Nom:'PUSHA';
  Code:caPUSHA;
  CPU:p80286Plus;
  Parameters:No;
  OpCode:#$60;
  Gauche:Ofs(acPUNPCKHBW);
  Droite:Ofs(acPUSHFW)
 );

 acREPNE:NoeudAsmRec=(
  Nom:'REPNE';
  Code:caREPNE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F2;
  Gauche:0;
  Droite:0
 );

 acREPE:NoeudAsmRec=(
  Nom:'REPE';
  Code:caREPE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F3;
  Gauche:0;
  Droite:Ofs(acREPNE)
 );

 acREPZ:NoeudAsmRec=(
  Nom:'REPZ';
  Code:caREPZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F3;
  Gauche:0;
  Droite:0
 );

 acRETF:NoeudAsmRec=(
  Nom:'RETF';
  Code:caRETF;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acRET:NoeudAsmRec=(
  Nom:'RET';
  Code:caRET;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acREPZ);
  Droite:Ofs(acRETF)
 );

 acREPNZ:NoeudAsmRec=(
  Nom:'REPNZ';
  Code:caREPNZ;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F2;
  Gauche:Ofs(acREPE);
  Droite:Ofs(acRET)
 );

 acROR:NoeudAsmRec=(
  Nom:'ROR';
  Code:caROR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$08;
  Gauche:0;
  Droite:0
 );

 acROL:NoeudAsmRec=(
  Nom:'ROL';
  Code:caROL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$00;
  Gauche:0;
  Droite:Ofs(acROR)
 );

 acSAHF:NoeudAsmRec=(
  Nom:'SAHF';
  Code:caSAHF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9E;
  Gauche:0;
  Droite:0
 );

 acSALC:NoeudAsmRec=(
  Nom:'SALC';
  Code:caSALC;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D6;
  Gauche:0;
  Droite:0
 );

 acSAL:NoeudAsmRec=(
  Nom:'SAL';
  Code:caSAL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$30;
  Gauche:Ofs(acSAHF);
  Droite:Ofs(acSALC)
 );

 acRSM:NoeudAsmRec=(
  Nom:'RSM';
  Code:caRSM;
  CPU:p80586Plus;
  Parameters:No;
  OpCode:#$0F#$AA;
  Gauche:Ofs(acROL);
  Droite:Ofs(acSAL)
 );

 acRETN:NoeudAsmRec=(
  Nom:'RETN';
  Code:caRETN;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acREPNZ);
  Droite:Ofs(acRSM)
 );

 acSBB:NoeudAsmRec=(
  Nom:'SBB';
  Code:caSBB;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$18;
  Gauche:0;
  Droite:0
 );

 acSAVEAHFLAGS:NoeudAsmRec=(
  Nom:'SAVEAHFLAGS';
  Code:caSAVEAHFLAGS;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9E;
  Gauche:0;
  Droite:Ofs(acSBB)
 );

 acSCASD:NoeudAsmRec=(
  Nom:'SCASD';
  Code:caSCASD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$AF;
  Gauche:0;
  Droite:0
 );

 acSETA:NoeudAsmRec=(
  Nom:'SETA';
  Code:caSETA;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$97;
  Gauche:0;
  Droite:0
 );

 acSCASW:NoeudAsmRec=(
  Nom:'SCASW';
  Code:caSCASW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AF;
  Gauche:Ofs(acSCASD);
  Droite:Ofs(acSETA)
 );

 acSCASB:NoeudAsmRec=(
  Nom:'SCASB';
  Code:caSCASB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AE;
  Gauche:Ofs(acSAVEAHFLAGS);
  Droite:Ofs(acSCASW)
 );

 acSETALC:NoeudAsmRec=(
  Nom:'SETALC';
  Code:caSETALC;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D6;
  Gauche:0;
  Droite:0
 );

 acSETBE:NoeudAsmRec=(
  Nom:'SETBE';
  Code:caSETBE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$96;
  Gauche:0;
  Droite:0
 );

 acSETB:NoeudAsmRec=(
  Nom:'SETB';
  Code:caSETB;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$92;
  Gauche:Ofs(acSETALC);
  Droite:Ofs(acSETBE)
 );

 acSETCARRY:NoeudAsmRec=(
  Nom:'SETCARRY';
  Code:caSETCARRY;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F9;
  Gauche:0;
  Droite:0
 );

 acSETD:NoeudAsmRec=(
  Nom:'SETD';
  Code:caSETD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FD;
  Gauche:0;
  Droite:0
 );

 acSETCF:NoeudAsmRec=(
  Nom:'SETCF';
  Code:caSETCF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F9;
  Gauche:Ofs(acSETCARRY);
  Droite:Ofs(acSETD)
 );

 acSETC:NoeudAsmRec=(
  Nom:'SETC';
  Code:caSETC;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$92;
  Gauche:Ofs(acSETB);
  Droite:Ofs(acSETCF)
 );

 acSETAE:NoeudAsmRec=(
  Nom:'SETAE';
  Code:caSETAE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$93;
  Gauche:Ofs(acSCASB);
  Droite:Ofs(acSETC)
 );

 acSAR:NoeudAsmRec=(
  Nom:'SAR';
  Code:caSAR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$38;
  Gauche:Ofs(acRETN);
  Droite:Ofs(acSETAE)
 );

 acREP:NoeudAsmRec=(
  Nom:'REP';
  Code:caREP;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$F3;
  Gauche:Ofs(acPUSHA);
  Droite:Ofs(acSAR)
 );

 acSETG:NoeudAsmRec=(
  Nom:'SETG';
  Code:caSETG;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9F;
  Gauche:0;
  Droite:0
 );

 acSETE:NoeudAsmRec=(
  Nom:'SETE';
  Code:caSETE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$94;
  Gauche:0;
  Droite:Ofs(acSETG)
 );

 acSETI:NoeudAsmRec=(
  Nom:'SETI';
  Code:caSETI;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FB;
  Gauche:0;
  Droite:0
 );

 acSETL:NoeudAsmRec=(
  Nom:'SETL';
  Code:caSETL;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9C;
  Gauche:0;
  Droite:0
 );

 acSETIF:NoeudAsmRec=(
  Nom:'SETIF';
  Code:caSETIF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FB;
  Gauche:Ofs(acSETI);
  Droite:Ofs(acSETL)
 );

 acSETGE:NoeudAsmRec=(
  Nom:'SETGE';
  Code:caSETGE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9D;
  Gauche:Ofs(acSETE);
  Droite:Ofs(acSETIF)
 );

 acSETNAE:NoeudAsmRec=(
  Nom:'SETNAE';
  Code:caSETNAE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$92;
  Gauche:0;
  Droite:0
 );

 acSETNA:NoeudAsmRec=(
  Nom:'SETNA';
  Code:caSETNA;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$96;
  Gauche:0;
  Droite:Ofs(acSETNAE)
 );

 acSETNC:NoeudAsmRec=(
  Nom:'SETNC';
  Code:caSETNC;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$93;
  Gauche:0;
  Droite:0
 );

 acSETNG:NoeudAsmRec=(
  Nom:'SETNG';
  Code:caSETNG;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9E;
  Gauche:0;
  Droite:0
 );

 acSETNE:NoeudAsmRec=(
  Nom:'SETNE';
  Code:caSETNE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$95;
  Gauche:Ofs(acSETNC);
  Droite:Ofs(acSETNG)
 );

 acSETNB:NoeudAsmRec=(
  Nom:'SETNB';
  Code:caSETNB;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$93;
  Gauche:Ofs(acSETNA);
  Droite:Ofs(acSETNE)
 );

 acSETLE:NoeudAsmRec=(
  Nom:'SETLE';
  Code:caSETLE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9E;
  Gauche:Ofs(acSETGE);
  Droite:Ofs(acSETNB)
 );

 acSETNLE:NoeudAsmRec=(
  Nom:'SETNLE';
  Code:caSETNLE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9F;
  Gauche:0;
  Droite:0
 );

 acSETNL:NoeudAsmRec=(
  Nom:'SETNL';
  Code:caSETNL;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9D;
  Gauche:0;
  Droite:Ofs(acSETNLE)
 );

 acSETNP:NoeudAsmRec=(
  Nom:'SETNP';
  Code:caSETNP;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9B;
  Gauche:0;
  Droite:0
 );

 acSETNZ:NoeudAsmRec=(
  Nom:'SETNZ';
  Code:caSETNZ;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$95;
  Gauche:0;
  Droite:0
 );

 acSETNS:NoeudAsmRec=(
  Nom:'SETNS';
  Code:caSETNS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$99;
  Gauche:Ofs(acSETNP);
  Droite:Ofs(acSETNZ)
 );

 acSETNO:NoeudAsmRec=(
  Nom:'SETNO';
  Code:caSETNO;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$91;
  Gauche:Ofs(acSETNL);
  Droite:Ofs(acSETNS)
 );

 acSETPE:NoeudAsmRec=(
  Nom:'SETPE';
  Code:caSETPE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9A;
  Gauche:0;
  Droite:0
 );

 acSETP:NoeudAsmRec=(
  Nom:'SETP';
  Code:caSETP;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9A;
  Gauche:0;
  Droite:Ofs(acSETPE)
 );

 acSETS:NoeudAsmRec=(
  Nom:'SETS';
  Code:caSETS;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$98;
  Gauche:0;
  Droite:0
 );

 acSGDT:NoeudAsmRec=(
  Nom:'SGDT';
  Code:caSGDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acSETZ:NoeudAsmRec=(
  Nom:'SETZ';
  Code:caSETZ;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$94;
  Gauche:Ofs(acSETS);
  Droite:Ofs(acSGDT)
 );

 acSETPO:NoeudAsmRec=(
  Nom:'SETPO';
  Code:caSETPO;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9B;
  Gauche:Ofs(acSETP);
  Droite:Ofs(acSETZ)
 );

 acSETO:NoeudAsmRec=(
  Nom:'SETO';
  Code:caSETO;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$90;
  Gauche:Ofs(acSETNO);
  Droite:Ofs(acSETPO)
 );

 acSETNGE:NoeudAsmRec=(
  Nom:'SETNGE';
  Code:caSETNGE;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:#$0F#$9C;
  Gauche:Ofs(acSETLE);
  Droite:Ofs(acSETO)
 );

 acSHR:NoeudAsmRec=(
  Nom:'SHR';
  Code:caSHR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$28;
  Gauche:0;
  Droite:0
 );

 acSHLD:NoeudAsmRec=(
  Nom:'SHLD';
  Code:caSHLD;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:Ofs(acSHR)
 );

 acSIDT:NoeudAsmRec=(
  Nom:'SIDT';
  Code:caSIDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acSMI:NoeudAsmRec=(
  Nom:'SMI';
  Code:caSMI;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$F1;
  Gauche:0;
  Droite:0
 );

 acSLDT:NoeudAsmRec=(
  Nom:'SLDT';
  Code:caSLDT;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acSIDT);
  Droite:Ofs(acSMI)
 );

 acSHRD:NoeudAsmRec=(
  Nom:'SHRD';
  Code:caSHRD;
  CPU:p80386Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acSHLD);
  Droite:Ofs(acSLDT)
 );

 acSTD:NoeudAsmRec=(
  Nom:'STD';
  Code:caSTD;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FD;
  Gauche:0;
  Droite:0
 );

 acSTC:NoeudAsmRec=(
  Nom:'STC';
  Code:caSTC;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$F9;
  Gauche:0;
  Droite:Ofs(acSTD)
 );

 acSTOSB:NoeudAsmRec=(
  Nom:'STOSB';
  Code:caSTOSB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AA;
  Gauche:0;
  Droite:0
 );

 acSTOSW:NoeudAsmRec=(
  Nom:'STOSW';
  Code:caSTOSW;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$AB;
  Gauche:0;
  Droite:0
 );

 acSTOSD:NoeudAsmRec=(
  Nom:'STOSD';
  Code:caSTOSD;
  CPU:p80386Plus;
  Parameters:No;
  OpCode:#$66#$AB;
  Gauche:Ofs(acSTOSB);
  Droite:Ofs(acSTOSW)
 );

 acSTI:NoeudAsmRec=(
  Nom:'STI';
  Code:caSTI;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FB;
  Gauche:Ofs(acSTC);
  Droite:Ofs(acSTOSD)
 );

 acSS:NoeudAsmRec=(
  Nom:'SS';
  Code:caSS;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$36;
  Gauche:Ofs(acSHRD);
  Droite:Ofs(acSTI)
 );

 acTEST:NoeudAsmRec=(
  Nom:'TEST';
  Code:caTEST;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acSUB:NoeudAsmRec=(
  Nom:'SUB';
  Code:caSUB;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$28;
  Gauche:0;
  Droite:Ofs(acTEST)
 );

 acVERR:NoeudAsmRec=(
  Nom:'VERR';
  Code:caVERR;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acWAIT:NoeudAsmRec=(
  Nom:'WAIT';
  Code:caWAIT;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$9B;
  Gauche:0;
  Droite:0
 );

 acVERW:NoeudAsmRec=(
  Nom:'VERW';
  Code:caVERW;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acVERR);
  Droite:Ofs(acWAIT)
 );

 acUMOV:NoeudAsmRec=(
  Nom:'UMOV';
  Code:caUMOV;
  CPU:p80386;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acSUB);
  Droite:Ofs(acVERW)
 );

 acWRMSR:NoeudAsmRec=(
  Nom:'WRMSR';
  Code:caWRMSR;
  CPU:p80586Plus;
  Parameters:No;
  OpCode:#$0F#$30;
  Gauche:0;
  Droite:0
 );

 acXBTS:NoeudAsmRec=(
  Nom:'XBTS';
  Code:caXBTS;
  CPU:p80386;
  Parameters:Ya;
  OpCode:'';
  Gauche:0;
  Droite:0
 );

 acXADD:NoeudAsmRec=(
  Nom:'XADD';
  Code:caXADD;
  CPU:p80486Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acWRMSR);
  Droite:Ofs(acXBTS)
 );

 acXLAT:NoeudAsmRec=(
  Nom:'XLAT';
  Code:caXLAT;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D7;
  Gauche:0;
  Droite:0
 );

 acXOR:NoeudAsmRec=(
  Nom:'XOR';
  Code:caXOR;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$30;
  Gauche:0;
  Droite:0
 );

 acXLATB:NoeudAsmRec=(
  Nom:'XLATB';
  Code:caXLATB;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$D7;
  Gauche:Ofs(acXLAT);
  Droite:Ofs(acXOR)
 );

 acXCHG:NoeudAsmRec=(
  Nom:'XCHG';
  Code:caXCHG;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acXADD);
  Droite:Ofs(acXLATB)
 );

 acWBINVD:NoeudAsmRec=(
  Nom:'WBINVD';
  Code:caWBINVD;
  CPU:p80486Plus;
  Parameters:No;
  OpCode:#$0F#$08;
  Gauche:Ofs(acUMOV);
  Droite:Ofs(acXCHG)
 );

 acSTR:NoeudAsmRec=(
  Nom:'STR';
  Code:caSTR;
  CPU:p80286Plus;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acSS);
  Droite:Ofs(acWBINVD)
 );

 acSHL:NoeudAsmRec=(
  Nom:'SHL';
  Code:caSHL;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$20;
  Gauche:Ofs(acSETNGE);
  Droite:Ofs(acSTR)
 );

 acSETDF:NoeudAsmRec=(
  Nom:'SETDF';
  Code:caSETDF;
  CPU:p8088Plus;
  Parameters:No;
  OpCode:#$FD;
  Gauche:Ofs(acREP);
  Droite:Ofs(acSHL)
 );

 acPSUBD:NoeudAsmRec=(
  Nom:'PSUBD';
  Code:caPSUBD;
  CPU:pMMX;
  Parameters:Ya;
  OpCode:'';
  Gauche:Ofs(acNOP386);
  Droite:Ofs(acSETDF)
 );

 AsmCode:NoeudAsmRec=(
  Nom:'JNGE';
  Code:caJNGE;
  CPU:p8088Plus;
  Parameters:Ya;
  OpCode:#$7C;
  Gauche:Ofs(acFILD);
  Droite:Ofs(acPSUBD)
 );

Const

  { Les constantes suivantes renferme l'arbre des }
  { pour un IF conditionnel en assembleur }

 aifA:NoeudIfCondAsmRec=(
  Nom:'A';
  Code:$76;
  Gauche:0;
  Droite:0
 );

 aifAF:NoeudIfCondAsmRec=(
  Nom:'AF';
  Code:$76;
  Gauche:0;
  Droite:0
 );

 aifAE:NoeudIfCondAsmRec=(
  Nom:'AE';
  Code:$72;
  Gauche:Ofs(aifA);
  Droite:Ofs(aifAF)
 );

 aifBE:NoeudIfCondAsmRec=(
  Nom:'BE';
  Code:$77;
  Gauche:0;
  Droite:0
 );

 aifC:NoeudIfCondAsmRec=(
  Nom:'C';
  Code:$73;
  Gauche:0;
  Droite:0
 );

 aifBF:NoeudIfCondAsmRec=(
  Nom:'BF';
  Code:$73;
  Gauche:Ofs(aifBE);
  Droite:Ofs(aifC)
 );

 aifB:NoeudIfCondAsmRec=(
  Nom:'B';
  Code:$73;
  Gauche:Ofs(aifAE);
  Droite:Ofs(aifBF)
 );

 aifCARRYFLAG:NoeudIfCondAsmRec=(
  Nom:'CARRYFLAG';
  Code:$73;
  Gauche:0;
  Droite:0
 );

 aifE:NoeudIfCondAsmRec=(
  Nom:'E';
  Code:$75;
  Gauche:0;
  Droite:0
 );

 aifCF:NoeudIfCondAsmRec=(
  Nom:'CF';
  Code:$73;
  Gauche:Ofs(aifCARRYFLAG);
  Droite:Ofs(aifE)
 );

 aifEQUAL:NoeudIfCondAsmRec=(
  Nom:'EQUAL';
  Code:$75;
  Gauche:0;
  Droite:0
 );

 aifGE:NoeudIfCondAsmRec=(
  Nom:'GE';
  Code:$7C;
  Gauche:0;
  Droite:0
 );

 aifG:NoeudIfCondAsmRec=(
  Nom:'G';
  Code:$7E;
  Gauche:0;
  Droite:Ofs(aifGE)
 );

 aifEQUALFLAG:NoeudIfCondAsmRec=(
  Nom:'EQUALFLAG';
  Code:$75;
  Gauche:Ofs(aifEQUAL);
  Droite:Ofs(aifG)
 );

 aifEF:NoeudIfCondAsmRec=(
  Nom:'EF';
  Code:$75;
  Gauche:Ofs(aifCF);
  Droite:Ofs(aifEQUALFLAG)
 );

 aifCARRY:NoeudIfCondAsmRec=(
  Nom:'CARRY';
  Code:$73;
  Gauche:Ofs(aifB);
  Droite:Ofs(aifEF)
 );

 aifGREAT:NoeudIfCondAsmRec=(
  Nom:'GREAT';
  Code:$7E;
  Gauche:0;
  Droite:0
 );

 aifL:NoeudIfCondAsmRec=(
  Nom:'L';
  Code:$7D;
  Gauche:0;
  Droite:0
 );

 aifGREATEQUAL:NoeudIfCondAsmRec=(
  Nom:'GREATEQUAL';
  Code:$7C;
  Gauche:Ofs(aifGREAT);
  Droite:Ofs(aifL)
 );

 aifLESS:NoeudIfCondAsmRec=(
  Nom:'LESS';
  Code:$7D;
  Gauche:0;
  Droite:0
 );

 aifLF:NoeudIfCondAsmRec=(
  Nom:'LF';
  Code:$7D;
  Gauche:0;
  Droite:0
 );

 aifLESSEQUAL:NoeudIfCondAsmRec=(
  Nom:'LESSEQUAL';
  Code:$7F;
  Gauche:Ofs(aifLESS);
  Droite:Ofs(aifLF)
 );

 aifLE:NoeudIfCondAsmRec=(
  Nom:'LE';
  Code:$7F;
  Gauche:Ofs(aifGREATEQUAL);
  Droite:Ofs(aifLESSEQUAL)
 );

 aifNA:NoeudIfCondAsmRec=(
  Nom:'NA';
  Code:$77;
  Gauche:0;
  Droite:0
 );

 aifNBE:NoeudIfCondAsmRec=(
  Nom:'NBE';
  Code:$76;
  Gauche:0;
  Droite:0
 );

 aifNB:NoeudIfCondAsmRec=(
  Nom:'NB';
  Code:$72;
  Gauche:Ofs(aifNA);
  Droite:Ofs(aifNBE)
 );

 aifNE:NoeudIfCondAsmRec=(
  Nom:'NE';
  Code:$74;
  Gauche:0;
  Droite:0
 );

 aifNL:NoeudIfCondAsmRec=(
  Nom:'NL';
  Code:$7C;
  Gauche:0;
  Droite:0
 );

 aifNGE:NoeudIfCondAsmRec=(
  Nom:'NGE';
  Code:$7D;
  Gauche:0;
  Droite:Ofs(aifNL)
 );

 aifNG:NoeudIfCondAsmRec=(
  Nom:'NG';
  Code:$7F;
  Gauche:Ofs(aifNE);
  Droite:Ofs(aifNGE)
 );

 aifNC:NoeudIfCondAsmRec=(
  Nom:'NC';
  Code:$72;
  Gauche:Ofs(aifNB);
  Droite:Ofs(aifNG)
 );

 aifN0:NoeudIfCondAsmRec=(
  Nom:'N0';
  Code:$74;
  Gauche:Ofs(aifLE);
  Droite:Ofs(aifNC)
 );

 aifGF:NoeudIfCondAsmRec=(
  Nom:'GF';
  Code:$7E;
  Gauche:Ofs(aifCARRY);
  Droite:Ofs(aifN0)
 );

 aifNO:NoeudIfCondAsmRec=(
  Nom:'NO';
  Code:$70;
  Gauche:0;
  Droite:0
 );

 aifNOTEQUAL:NoeudIfCondAsmRec=(
  Nom:'NOTEQUAL';
  Code:$74;
  Gauche:0;
  Droite:0
 );

 aifNOT0:NoeudIfCondAsmRec=(
  Nom:'NOT0';
  Code:$74;
  Gauche:Ofs(aifNO);
  Droite:Ofs(aifNOTEQUAL)
 );

 aifNOTGREATEQUAL:NoeudIfCondAsmRec=(
  Nom:'NOTGREATEQUAL';
  Code:$7D;
  Gauche:0;
  Droite:0
 );

 aifNOTPARITY:NoeudIfCondAsmRec=(
  Nom:'NOTPARITY';
  Code:$7A;
  Gauche:0;
  Droite:0
 );

 aifNOTOVERFLOWFLAG:NoeudIfCondAsmRec=(
  Nom:'NOTOVERFLOWFLAG';
  Code:$70;
  Gauche:Ofs(aifNOTGREATEQUAL);
  Droite:Ofs(aifNOTPARITY)
 );

 aifNOTGREAT:NoeudIfCondAsmRec=(
  Nom:'NOTGREAT';
  Code:$7F;
  Gauche:Ofs(aifNOT0);
  Droite:Ofs(aifNOTOVERFLOWFLAG)
 );

 aifNOTSIGN:NoeudIfCondAsmRec=(
  Nom:'NOTSIGN';
  Code:$78;
  Gauche:0;
  Droite:0
 );

 aifNOTZERO:NoeudIfCondAsmRec=(
  Nom:'NOTZERO';
  Code:$74;
  Gauche:0;
  Droite:0
 );

 aifNOTSIGNFLAG:NoeudIfCondAsmRec=(
  Nom:'NOTSIGNFLAG';
  Code:$78;
  Gauche:Ofs(aifNOTSIGN);
  Droite:Ofs(aifNOTZERO)
 );

 aifNPF:NoeudIfCondAsmRec=(
  Nom:'NPF';
  Code:$7A;
  Gauche:0;
  Droite:0
 );

 aifNZ:NoeudIfCondAsmRec=(
  Nom:'NZ';
  Code:$74;
  Gauche:0;
  Droite:0
 );

 aifNSF:NoeudIfCondAsmRec=(
  Nom:'NSF';
  Code:$78;
  Gauche:0;
  Droite:Ofs(aifNZ)
 );

 aifNS:NoeudIfCondAsmRec=(
  Nom:'NS';
  Code:$78;
  Gauche:Ofs(aifNPF);
  Droite:Ofs(aifNSF)
 );

 aifNP:NoeudIfCondAsmRec=(
  Nom:'NP';
  Code:$7A;
  Gauche:Ofs(aifNOTSIGNFLAG);
  Droite:Ofs(aifNS)
 );

 aifNOTPARITYFLAG:NoeudIfCondAsmRec=(
  Nom:'NOTPARITYFLAG';
  Code:$7A;
  Gauche:Ofs(aifNOTGREAT);
  Droite:Ofs(aifNP)
 );

 aifO:NoeudIfCondAsmRec=(
  Nom:'O';
  Code:$71;
  Gauche:0;
  Droite:0
 );

 aifOVERFLOW:NoeudIfCondAsmRec=(
  Nom:'OVERFLOW';
  Code:$71;
  Gauche:0;
  Droite:0
 );

 aifOF:NoeudIfCondAsmRec=(
  Nom:'OF';
  Code:$71;
  Gauche:Ofs(aifO);
  Droite:Ofs(aifOVERFLOW)
 );

 aifP:NoeudIfCondAsmRec=(
  Nom:'P';
  Code:$7B;
  Gauche:0;
  Droite:0
 );

 aifPARITYFLAG:NoeudIfCondAsmRec=(
  Nom:'PARITYFLAG';
  Code:$7B;
  Gauche:0;
  Droite:0
 );

 aifPARITY:NoeudIfCondAsmRec=(
  Nom:'PARITY';
  Code:$7B;
  Gauche:Ofs(aifP);
  Droite:Ofs(aifPARITYFLAG)
 );

 aifOVERFLOWFLAG:NoeudIfCondAsmRec=(
  Nom:'OVERFLOWFLAG';
  Code:$71;
  Gauche:Ofs(aifOF);
  Droite:Ofs(aifPARITY)
 );

 aifS:NoeudIfCondAsmRec=(
  Nom:'S';
  Code:$79;
  Gauche:0;
  Droite:0
 );

 aifSIGN:NoeudIfCondAsmRec=(
  Nom:'SIGN';
  Code:$79;
  Gauche:0;
  Droite:0
 );

 aifSF:NoeudIfCondAsmRec=(
  Nom:'SF';
  Code:$79;
  Gauche:Ofs(aifS);
  Droite:Ofs(aifSIGN)
 );

 aifZ:NoeudIfCondAsmRec=(
  Nom:'Z';
  Code:$75;
  Gauche:0;
  Droite:0
 );

 aifZEROFLAG:NoeudIfCondAsmRec=(
  Nom:'ZEROFLAG';
  Code:$75;
  Gauche:0;
  Droite:0
 );

 aifZERO:NoeudIfCondAsmRec=(
  Nom:'ZERO';
  Code:$75;
  Gauche:0;
  Droite:Ofs(aifZEROFLAG)
 );

 aifZF:NoeudIfCondAsmRec=(
  Nom:'ZF';
  Code:$75;
  Gauche:Ofs(aifZ);
  Droite:Ofs(aifZERO)
 );

 aifSIGNFLAG:NoeudIfCondAsmRec=(
  Nom:'SIGNFLAG';
  Code:$79;
  Gauche:Ofs(aifSF);
  Droite:Ofs(aifZF)
 );

 aifPF:NoeudIfCondAsmRec=(
  Nom:'PF';
  Code:$7B;
  Gauche:Ofs(aifOVERFLOWFLAG);
  Droite:Ofs(aifSIGNFLAG)
 );

 aifNZERO:NoeudIfCondAsmRec=(
  Nom:'NZERO';
  Code:$74;
  Gauche:Ofs(aifNOTPARITYFLAG);
  Droite:Ofs(aifPF)
 );

 AsmIfCond:NoeudIfCondAsmRec=(
  Nom:'NLE';
  Code:$7E;
  Gauche:Ofs(aifGF);
  Droite:Ofs(aifNZERO)
 );

Const

  { Les constantes suivantes renferme l'arbre des }
  { mots r‚serv‚s en Pascal … l''entr‚e }

 mwpABSOLUTE:NoeudMainWordPasRec=(
  Nom:'ABSOLUTE';
  Code:27;
  Gauche:0;
  Droite:0
 );

 mwpABSOLUE:NoeudMainWordPasRec=(
  Nom:'ABSOLUE';
  Code:27;
  Gauche:0;
  Droite:Ofs(mwpABSOLUTE)
 );

 mwpALORS:NoeudMainWordPasRec=(
  Nom:'ALORS';
  Code:22;
  Gauche:0;
  Droite:0
 );

 mwpARRAY:NoeudMainWordPasRec=(
  Nom:'ARRAY';
  Code:29;
  Gauche:0;
  Droite:0
 );

 mwpAND:NoeudMainWordPasRec=(
  Nom:'AND';
  Code:28;
  Gauche:Ofs(mwpALORS);
  Droite:Ofs(mwpARRAY)
 );

 mwpALLERA:NoeudMainWordPasRec=(
  Nom:'ALLERA';
  Code:24;
  Gauche:Ofs(mwpABSOLUE);
  Droite:Ofs(mwpAND)
 );

 mwpASSEMBLE:NoeudMainWordPasRec=(
  Nom:'ASSEMBLE';
  Code:0;
  Gauche:0;
  Droite:0
 );

 mwpASSEMBLEUR:NoeudMainWordPasRec=(
  Nom:'ASSEMBLEUR';
  Code:30;
  Gauche:0;
  Droite:0
 );

 mwpASSEMBLER:NoeudMainWordPasRec=(
  Nom:'ASSEMBLER';
  Code:30;
  Gauche:Ofs(mwpASSEMBLE);
  Droite:Ofs(mwpASSEMBLEUR)
 );

 mwpAVEC:NoeudMainWordPasRec=(
  Nom:'AVEC';
  Code:49;
  Gauche:0;
  Droite:0
 );

 mwpBIBLIOTHEQUE:NoeudMainWordPasRec=(
  Nom:'BIBLIOTHEQUE';
  Code:11;
  Gauche:0;
  Droite:0
 );

 mwpBEGIN:NoeudMainWordPasRec=(
  Nom:'BEGIN';
  Code:1;
  Gauche:Ofs(mwpAVEC);
  Droite:Ofs(mwpBIBLIOTHEQUE)
 );

 mwpAUTREMENT:NoeudMainWordPasRec=(
  Nom:'AUTREMENT';
  Code:21;
  Gauche:Ofs(mwpASSEMBLER);
  Droite:Ofs(mwpBEGIN)
 );

 mwpASM:NoeudMainWordPasRec=(
  Nom:'ASM';
  Code:0;
  Gauche:Ofs(mwpALLERA);
  Droite:Ofs(mwpAUTREMENT)
 );

 mwpCODECONST:NoeudMainWordPasRec=(
  Nom:'CODECONST';
  Code:2;
  Gauche:0;
  Droite:0
 );

 mwpCASE:NoeudMainWordPasRec=(
  Nom:'CASE';
  Code:31;
  Gauche:0;
  Droite:Ofs(mwpCODECONST)
 );

 mwpCONSTANT:NoeudMainWordPasRec=(
  Nom:'CONSTANT';
  Code:3;
  Gauche:0;
  Droite:0
 );

 mwpCONSTRUCTEUR:NoeudMainWordPasRec=(
  Nom:'CONSTRUCTEUR';
  Code:32;
  Gauche:0;
  Droite:0
 );

 mwpCONSTANTE:NoeudMainWordPasRec=(
  Nom:'CONSTANTE';
  Code:3;
  Gauche:Ofs(mwpCONSTANT);
  Droite:Ofs(mwpCONSTRUCTEUR)
 );

 mwpCONST:NoeudMainWordPasRec=(
  Nom:'CONST';
  Code:3;
  Gauche:Ofs(mwpCASE);
  Droite:Ofs(mwpCONSTANTE)
 );

 mwpCSCONST:NoeudMainWordPasRec=(
  Nom:'CSCONST';
  Code:2;
  Gauche:0;
  Droite:0
 );

 mwpDANS:NoeudMainWordPasRec=(
  Nom:'DANS';
  Code:37;
  Gauche:0;
  Droite:0
 );

 mwpCSDATA:NoeudMainWordPasRec=(
  Nom:'CSDATA';
  Code:2;
  Gauche:Ofs(mwpCSCONST);
  Droite:Ofs(mwpDANS)
 );

 mwpDEBUT:NoeudMainWordPasRec=(
  Nom:'DEBUT';
  Code:1;
  Gauche:0;
  Droite:0
 );

 mwpDECALG:NoeudMainWordPasRec=(
  Nom:'DECALG';
  Code:54;
  Gauche:0;
  Droite:0
 );

 mwpDECALD:NoeudMainWordPasRec=(
  Nom:'DECALD';
  Code:55;
  Gauche:Ofs(mwpDEBUT);
  Droite:Ofs(mwpDECALG)
 );

 mwpDE:NoeudMainWordPasRec=(
  Nom:'DE';
  Code:43;
  Gauche:Ofs(mwpCSDATA);
  Droite:Ofs(mwpDECALD)
 );

 mwpCONSTRUCTOR:NoeudMainWordPasRec=(
  Nom:'CONSTRUCTOR';
  Code:32;
  Gauche:Ofs(mwpCONST);
  Droite:Ofs(mwpDE)
 );

 mwpCAS:NoeudMainWordPasRec=(
  Nom:'CAS';
  Code:31;
  Gauche:Ofs(mwpASM);
  Droite:Ofs(mwpCONSTRUCTOR)
 );

 mwpDESTRUCTEUR:NoeudMainWordPasRec=(
  Nom:'DESTRUCTEUR';
  Code:33;
  Gauche:0;
  Droite:0
 );

 mwpDEG:NoeudMainWordPasRec=(
  Nom:'DEG';
  Code:54;
  Gauche:0;
  Droite:Ofs(mwpDESTRUCTEUR)
 );

 mwpDIV:NoeudMainWordPasRec=(
  Nom:'DIV';
  Code:50;
  Gauche:0;
  Droite:0
 );

 mwpDUPLICATE:NoeudMainWordPasRec=(
  Nom:'DUPLICATE';
  Code:59;
  Gauche:0;
  Droite:0
 );

 mwpDO:NoeudMainWordPasRec=(
  Nom:'DO';
  Code:34;
  Gauche:Ofs(mwpDIV);
  Droite:Ofs(mwpDUPLICATE)
 );

 mwpDESTRUCTOR:NoeudMainWordPasRec=(
  Nom:'DESTRUCTOR';
  Code:33;
  Gauche:Ofs(mwpDEG);
  Droite:Ofs(mwpDO)
 );

 mwpDUPLIQUE:NoeudMainWordPasRec=(
  Nom:'DUPLIQUE';
  Code:59;
  Gauche:0;
  Droite:0
 );

 mwpELSE:NoeudMainWordPasRec=(
  Nom:'ELSE';
  Code:21;
  Gauche:0;
  Droite:0
 );

 mwpELIF:NoeudMainWordPasRec=(
  Nom:'ELIF';
  Code:58;
  Gauche:Ofs(mwpDUPLIQUE);
  Droite:Ofs(mwpELSE)
 );

 mwpELSIF:NoeudMainWordPasRec=(
  Nom:'ELSIF';
  Code:58;
  Gauche:0;
  Droite:0
 );

 mwpENLIGNE:NoeudMainWordPasRec=(
  Nom:'ENLIGNE';
  Code:39;
  Gauche:0;
  Droite:0
 );

 mwpEND:NoeudMainWordPasRec=(
  Nom:'END';
  Code:19;
  Gauche:Ofs(mwpELSIF);
  Droite:Ofs(mwpENLIGNE)
 );

 mwpELSEIF:NoeudMainWordPasRec=(
  Nom:'ELSEIF';
  Code:58;
  Gauche:Ofs(mwpELIF);
  Droite:Ofs(mwpEND)
 );

 mwpDUPLICATION:NoeudMainWordPasRec=(
  Nom:'DUPLICATION';
  Code:59;
  Gauche:Ofs(mwpDESTRUCTOR);
  Droite:Ofs(mwpELSEIF)
 );

 mwpENSEMBLE:NoeudMainWordPasRec=(
  Nom:'ENSEMBLE';
  Code:46;
  Gauche:0;
  Droite:0
 );

 mwpETIQUETTE:NoeudMainWordPasRec=(
  Nom:'ETIQUETTE';
  Code:40;
  Gauche:0;
  Droite:0
 );

 mwpET:NoeudMainWordPasRec=(
  Nom:'ET';
  Code:28;
  Gauche:Ofs(mwpENSEMBLE);
  Droite:Ofs(mwpETIQUETTE)
 );

 mwpFAIRE:NoeudMainWordPasRec=(
  Nom:'FAIRE';
  Code:34;
  Gauche:0;
  Droite:0
 );

 mwpFICHIER:NoeudMainWordPasRec=(
  Nom:'FICHIER';
  Code:36;
  Gauche:0;
  Droite:0
 );

 mwpFAR:NoeudMainWordPasRec=(
  Nom:'FAR';
  Code:35;
  Gauche:Ofs(mwpFAIRE);
  Droite:Ofs(mwpFICHIER)
 );

 mwpEXPORTS:NoeudMainWordPasRec=(
  Nom:'EXPORTS';
  Code:4;
  Gauche:Ofs(mwpET);
  Droite:Ofs(mwpFAR)
 );

 mwpFIN:NoeudMainWordPasRec=(
  Nom:'FIN';
  Code:19;
  Gauche:0;
  Droite:0
 );

 mwpFINALIZATION:NoeudMainWordPasRec=(
  Nom:'FINALIZATION';
  Code:5;
  Gauche:0;
  Droite:0
 );

 mwpFINALISATION:NoeudMainWordPasRec=(
  Nom:'FINALISATION';
  Code:5;
  Gauche:Ofs(mwpFIN);
  Droite:Ofs(mwpFINALIZATION)
 );

 mwpFOR:NoeudMainWordPasRec=(
  Nom:'FOR';
  Code:23;
  Gauche:0;
  Droite:0
 );

 mwpGOTO:NoeudMainWordPasRec=(
  Nom:'GOTO';
  Code:24;
  Gauche:0;
  Droite:0
 );

 mwpFUNCTION:NoeudMainWordPasRec=(
  Nom:'FUNCTION';
  Code:6;
  Gauche:Ofs(mwpFOR);
  Droite:Ofs(mwpGOTO)
 );

 mwpFONCTION:NoeudMainWordPasRec=(
  Nom:'FONCTION';
  Code:6;
  Gauche:Ofs(mwpFINALISATION);
  Droite:Ofs(mwpFUNCTION)
 );

 mwpFILE:NoeudMainWordPasRec=(
  Nom:'FILE';
  Code:36;
  Gauche:Ofs(mwpEXPORTS);
  Droite:Ofs(mwpFONCTION)
 );

 mwpENREGISTREMENT:NoeudMainWordPasRec=(
  Nom:'ENREGISTREMENT';
  Code:45;
  Gauche:Ofs(mwpDUPLICATION);
  Droite:Ofs(mwpFILE)
 );

 mwpDED:NoeudMainWordPasRec=(
  Nom:'DED';
  Code:55;
  Gauche:Ofs(mwpCAS);
  Droite:Ofs(mwpENREGISTREMENT)
 );

 mwpIMPLEMENTATION:NoeudMainWordPasRec=(
  Nom:'IMPLEMENTATION';
  Code:7;
  Gauche:0;
  Droite:0
 );

 mwpIF:NoeudMainWordPasRec=(
  Nom:'IF';
  Code:20;
  Gauche:0;
  Droite:Ofs(mwpIMPLEMENTATION)
 );

 mwpINCLUDE:NoeudMainWordPasRec=(
  Nom:'INCLUDE';
  Code:8;
  Gauche:0;
  Droite:0
 );

 mwpINLINE:NoeudMainWordPasRec=(
  Nom:'INLINE';
  Code:39;
  Gauche:0;
  Droite:0
 );

 mwpINHERITED:NoeudMainWordPasRec=(
  Nom:'INHERITED';
  Code:38;
  Gauche:Ofs(mwpINCLUDE);
  Droite:Ofs(mwpINLINE)
 );

 mwpIN:NoeudMainWordPasRec=(
  Nom:'IN';
  Code:37;
  Gauche:Ofs(mwpIF);
  Droite:Ofs(mwpINHERITED)
 );

 mwpINITIALIZATION:NoeudMainWordPasRec=(
  Nom:'INITIALIZATION';
  Code:9;
  Gauche:0;
  Droite:0
 );

 mwpINTERRUPT:NoeudMainWordPasRec=(
  Nom:'INTERRUPT';
  Code:57;
  Gauche:0;
  Droite:0
 );

 mwpINTERFACE:NoeudMainWordPasRec=(
  Nom:'INTERFACE';
  Code:10;
  Gauche:Ofs(mwpINITIALIZATION);
  Droite:Ofs(mwpINTERRUPT)
 );

 mwpLABEL:NoeudMainWordPasRec=(
  Nom:'LABEL';
  Code:40;
  Gauche:0;
  Droite:0
 );

 mwpLOIN:NoeudMainWordPasRec=(
  Nom:'LOIN';
  Code:35;
  Gauche:0;
  Droite:0
 );

 mwpLIBRARY:NoeudMainWordPasRec=(
  Nom:'LIBRARY';
  Code:11;
  Gauche:Ofs(mwpLABEL);
  Droite:Ofs(mwpLOIN)
 );

 mwpJUSQUA:NoeudMainWordPasRec=(
  Nom:'JUSQUA';
  Code:47;
  Gauche:Ofs(mwpINTERFACE);
  Droite:Ofs(mwpLIBRARY)
 );

 mwpINITIALISATION:NoeudMainWordPasRec=(
  Nom:'INITIALISATION';
  Code:9;
  Gauche:Ofs(mwpIN);
  Droite:Ofs(mwpJUSQUA)
 );

 mwpNEAR:NoeudMainWordPasRec=(
  Nom:'NEAR';
  Code:41;
  Gauche:0;
  Droite:0
 );

 mwpMOD:NoeudMainWordPasRec=(
  Nom:'MOD';
  Code:51;
  Gauche:0;
  Droite:Ofs(mwpNEAR)
 );

 mwpOBJECT:NoeudMainWordPasRec=(
  Nom:'OBJECT';
  Code:42;
  Gauche:0;
  Droite:0
 );

 mwpOF:NoeudMainWordPasRec=(
  Nom:'OF';
  Code:43;
  Gauche:0;
  Droite:0
 );

 mwpOBJET:NoeudMainWordPasRec=(
  Nom:'OBJET';
  Code:42;
  Gauche:Ofs(mwpOBJECT);
  Droite:Ofs(mwpOF)
 );

 mwpNOT:NoeudMainWordPasRec=(
  Nom:'NOT';
  Code:52;
  Gauche:Ofs(mwpMOD);
  Droite:Ofs(mwpOBJET)
 );

 mwpOU:NoeudMainWordPasRec=(
  Nom:'OU';
  Code:53;
  Gauche:0;
  Droite:0
 );

 mwpPACKED:NoeudMainWordPasRec=(
  Nom:'PACKED';
  Code:44;
  Gauche:0;
  Droite:0
 );

 mwpOUX:NoeudMainWordPasRec=(
  Nom:'OUX';
  Code:56;
  Gauche:Ofs(mwpOU);
  Droite:Ofs(mwpPACKED)
 );

 mwpPAS:NoeudMainWordPasRec=(
  Nom:'PAS';
  Code:52;
  Gauche:0;
  Droite:0
 );

 mwpPROCEDURE:NoeudMainWordPasRec=(
  Nom:'PROCEDURE';
  Code:13;
  Gauche:0;
  Droite:0
 );

 mwpPOUR:NoeudMainWordPasRec=(
  Nom:'POUR';
  Code:23;
  Gauche:Ofs(mwpPAS);
  Droite:Ofs(mwpPROCEDURE)
 );

 mwpPAQUET:NoeudMainWordPasRec=(
  Nom:'PAQUET';
  Code:44;
  Gauche:Ofs(mwpOUX);
  Droite:Ofs(mwpPOUR)
 );

 mwpOR:NoeudMainWordPasRec=(
  Nom:'OR';
  Code:53;
  Gauche:Ofs(mwpNOT);
  Droite:Ofs(mwpPAQUET)
 );

 mwpMACRO:NoeudMainWordPasRec=(
  Nom:'MACRO';
  Code:12;
  Gauche:Ofs(mwpINITIALISATION);
  Droite:Ofs(mwpOR)
 );

 mwpPROGRAMME:NoeudMainWordPasRec=(
  Nom:'PROGRAMME';
  Code:14;
  Gauche:0;
  Droite:0
 );

 mwpPROGRAM:NoeudMainWordPasRec=(
  Nom:'PROGRAM';
  Code:14;
  Gauche:0;
  Droite:Ofs(mwpPROGRAMME)
 );

 mwpRECORD:NoeudMainWordPasRec=(
  Nom:'RECORD';
  Code:45;
  Gauche:0;
  Droite:0
 );

 mwpREGISTRE:NoeudMainWordPasRec=(
  Nom:'REGISTRE';
  Code:60;
  Gauche:0;
  Droite:0
 );

 mwpREGISTER:NoeudMainWordPasRec=(
  Nom:'REGISTER';
  Code:60;
  Gauche:Ofs(mwpRECORD);
  Droite:Ofs(mwpREGISTRE)
 );

 mwpRANGEE:NoeudMainWordPasRec=(
  Nom:'RANGEE';
  Code:29;
  Gauche:Ofs(mwpPROGRAM);
  Droite:Ofs(mwpREGISTER)
 );

 mwpREPETER:NoeudMainWordPasRec=(
  Nom:'REPETER';
  Code:26;
  Gauche:0;
  Droite:0
 );

 mwpSHL:NoeudMainWordPasRec=(
  Nom:'SHL';
  Code:54;
  Gauche:0;
  Droite:0
 );

 mwpSET:NoeudMainWordPasRec=(
  Nom:'SET';
  Code:46;
  Gauche:Ofs(mwpREPETER);
  Droite:Ofs(mwpSHL)
 );

 mwpSI:NoeudMainWordPasRec=(
  Nom:'SI';
  Code:20;
  Gauche:0;
  Droite:0
 );

 mwpTANTQUE:NoeudMainWordPasRec=(
  Nom:'TANTQUE';
  Code:25;
  Gauche:0;
  Droite:0
 );

 mwpSINON:NoeudMainWordPasRec=(
  Nom:'SINON';
  Code:21;
  Gauche:Ofs(mwpSI);
  Droite:Ofs(mwpTANTQUE)
 );

 mwpSHR:NoeudMainWordPasRec=(
  Nom:'SHR';
  Code:55;
  Gauche:Ofs(mwpSET);
  Droite:Ofs(mwpSINON)
 );

 mwpREPEAT:NoeudMainWordPasRec=(
  Nom:'REPEAT';
  Code:26;
  Gauche:Ofs(mwpRANGEE);
  Droite:Ofs(mwpSHR)
 );

 mwpTO:NoeudMainWordPasRec=(
  Nom:'TO';
  Code:47;
  Gauche:0;
  Droite:0
 );

 mwpTYPE:NoeudMainWordPasRec=(
  Nom:'TYPE';
  Code:15;
  Gauche:0;
  Droite:0
 );

 mwpTTQ:NoeudMainWordPasRec=(
  Nom:'TTQ';
  Code:25;
  Gauche:Ofs(mwpTO);
  Droite:Ofs(mwpTYPE)
 );

 mwpUNIT:NoeudMainWordPasRec=(
  Nom:'UNIT';
  Code:16;
  Gauche:0;
  Droite:0
 );

 mwpUSES:NoeudMainWordPasRec=(
  Nom:'USES';
  Code:17;
  Gauche:0;
  Droite:0
 );

 mwpUNITE:NoeudMainWordPasRec=(
  Nom:'UNITE';
  Code:16;
  Gauche:Ofs(mwpUNIT);
  Droite:Ofs(mwpUSES)
 );

 mwpTYPEDEF:NoeudMainWordPasRec=(
  Nom:'TYPEDEF';
  Code:15;
  Gauche:Ofs(mwpTTQ);
  Droite:Ofs(mwpUNITE)
 );

 mwpVAR:NoeudMainWordPasRec=(
  Nom:'VAR';
  Code:18;
  Gauche:0;
  Droite:0
 );

 mwpVIRTUAL:NoeudMainWordPasRec=(
  Nom:'VIRTUAL';
  Code:48;
  Gauche:0;
  Droite:0
 );

 mwpVARIABLE:NoeudMainWordPasRec=(
  Nom:'VARIABLE';
  Code:18;
  Gauche:Ofs(mwpVAR);
  Droite:Ofs(mwpVIRTUAL)
 );

 mwpWHILE:NoeudMainWordPasRec=(
  Nom:'WHILE';
  Code:25;
  Gauche:0;
  Droite:0
 );

 mwpXOR:NoeudMainWordPasRec=(
  Nom:'XOR';
  Code:56;
  Gauche:0;
  Droite:0
 );

 mwpWITH:NoeudMainWordPasRec=(
  Nom:'WITH';
  Code:49;
  Gauche:Ofs(mwpWHILE);
  Droite:Ofs(mwpXOR)
 );

 mwpVIRTUEL:NoeudMainWordPasRec=(
  Nom:'VIRTUEL';
  Code:48;
  Gauche:Ofs(mwpVARIABLE);
  Droite:Ofs(mwpWITH)
 );

 mwpUTILISES:NoeudMainWordPasRec=(
  Nom:'UTILISES';
  Code:17;
  Gauche:Ofs(mwpTYPEDEF);
  Droite:Ofs(mwpVIRTUEL)
 );

 mwpTHEN:NoeudMainWordPasRec=(
  Nom:'THEN';
  Code:22;
  Gauche:Ofs(mwpREPEAT);
  Droite:Ofs(mwpUTILISES)
 );

 mwpPROCHE:NoeudMainWordPasRec=(
  Nom:'PROCHE';
  Code:41;
  Gauche:Ofs(mwpMACRO);
  Droite:Ofs(mwpTHEN)
 );

 MainWordPas:NoeudMainWordPasRec=(
  Nom:'HERITIER';
  Code:38;
  Gauche:Ofs(mwpDED);
  Droite:Ofs(mwpPROCHE)
 );

Const
 cipAPPEND=0;                 { Instruction ®APPEND¯ }
 cipASSIGN=1;                 { Instruction ®ASSIGN¯ }
 cipBLOCKREAD=4;              { Instruction ®BLOCKREAD¯ }
 cipBLOCKWRITE=5;             { Instruction ®BLOCKWRITE¯ }
 cipBREAK=6;                  { Instruction ®BREAK¯ }
 cipCHDIR=8;                  { Instruction ®CHDIR¯ }
 cipCLI=9;                    { Instruction ®CLI¯ }
 cipCLOSE=10;                 { Instruction ®CLOSE¯ }
 cipCONCAT=11;                { Instruction ®CONCAT¯ }
 cipCONTINUE=12;              { Instruction ®CONTINUE¯ }
 cipDEC=13;                   { Instruction ®DEC¯ }
 cipDELETE=14;                { Instruction ®DELETE¯ }
 cipDISABLE=9;                { Instruction ®DISABLE¯ }
 cipDISPOSE=15;               { Instruction ®DISPOSE¯ }
 cipENABLE=19;                { Instruction ®ENABLE¯ }
 cipERASE=21;                 { Instruction ®ERASE¯ }
 cipEXCLUDE=22;               { Instruction ®EXCLUDE¯ }
 cipEXIT=23;                  { Instruction ®EXIT¯ }
 cipFILLCHAR=24;              { Instruction ®FILLCHAR¯ }
 cipFLUSH=25;                 { Instruction ®FLUSH¯ }
 cipFREEMEM=27;               { Instruction ®FREEMEM¯ }
 cipGENINTERRUPT=28;          { Instruction ®GENINTERRUPT¯ }
 cipGETDIR=29;                { Instruction ®GETDIR¯ }
 cipGETMEM=30;                { Instruction ®GETMEM¯ }
 cipHALT=32;                  { Instruction ®HALT¯ }
 cipINC=34;                   { Instruction ®INC¯ }
 cipINSERT=36;                { Instruction ®INSERT¯ }
 cipINTR=28;                  { Instruction ®INTR¯ }
 cipMARK=29;                  { Instruction ®MARK¯ }
 cipMEM=30;                   { Instruction ®MEM¯ }
 cipMEMW=31;                  { Instruction ®MEMW¯ }
 cipMKDIR=32;                 { Instruction ®MKDIR¯ }
 cipMOVE=33;                  { Instruction ®MOVE¯ }
 cipMOVELEFT=33;              { Instruction ®MOVELEFT¯ }
 cipMOVERIGHT=34;             { Instruction ®MOVERIGHT¯ }
 cipMSDOS=35;                 { Instruction ®MSDOS¯ }
 cipNEW=36;                   { Instruction ®NEW¯ }
 cipPORT=37;                  { Instruction ®PORT¯ }
 cipPORTW=38;                 { Instruction ®PORTW¯ }
 cipRANDOMIZE=39;             { Instruction ®RANDOMIZE¯ }
 cipREAD=40;                  { Instruction ®READ¯ }
 cipREADLN=41;                { Instruction ®READLN¯ }
 cipRELEASE=42;               { Instruction ®RELEASE¯ }
 cipRENAME=43;                { Instruction ®RENAME¯ }
 cipRESET=45;                 { Instruction ®RESET¯ }
 cipREWRITE=46;               { Instruction ®REWRITE¯ }
 cipRMDIR=47;                 { Instruction ®RMDIR¯ }
 cipRUNERROR=48;              { Instruction ®RUNERROR¯ }
 cipSEEK=49;                  { Instruction ®SEEK¯ }
 cipSETTEXTBUF=50;            { Instruction ®SETTEXTBUF¯ }
 cipSTI=51;                   { Instruction ®STI¯ }
 cipSTR=52;                   { Instruction ®STR¯ }
 cipVAL=54;                   { Instruction ®VAL¯ }
 cipWRITE=57;                 { Instruction ®WRITE¯ }
 cipWRITELN=58;               { Instruction ®WRITELN¯ }
 cip_CF=66;                   { Instruction ®_CF¯ }
 cip_DF=70;                   { Instruction ®_DF¯ }
 cip_IF=87;                   { Instruction ®_IF¯ }

  { Les constantes suivantes renferme l'arbre des }
  { instruction en Pascal B57 }

 ipASSIGN:NoeudInstrPasRec=(
  Nom:'ASSIGN';
  Code:cipASSIGN;
  Extra:1;
  Gauche:0;
  Droite:0
 );

 ipAPPEND:NoeudInstrPasRec=(
  Nom:'APPEND';
  Code:cipAPPEND;
  Extra:0;
  Gauche:0;
  Droite:Ofs(ipASSIGN)
 );

 ipBLOCKWRITE:NoeudInstrPasRec=(
  Nom:'BLOCKWRITE';
  Code:cipBLOCKWRITE;
  Extra:5;
  Gauche:0;
  Droite:0
 );

 ipCHDIR:NoeudInstrPasRec=(
  Nom:'CHDIR';
  Code:cipCHDIR;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 ipBREAK:NoeudInstrPasRec=(
  Nom:'BREAK';
  Code:cipBREAK;
  Extra:6;
  Gauche:Ofs(ipBLOCKWRITE);
  Droite:Ofs(ipCHDIR)
 );

 ipBLOCKREAD:NoeudInstrPasRec=(
  Nom:'BLOCKREAD';
  Code:cipBLOCKREAD;
  Extra:4;
  Gauche:Ofs(ipAPPEND);
  Droite:Ofs(ipBREAK)
 );

 ipCONCAT:NoeudInstrPasRec=(
  Nom:'CONCAT';
  Code:cipCONCAT;
  Extra:11;
  Gauche:0;
  Droite:0
 );

 ipCLOSE:NoeudInstrPasRec=(
  Nom:'CLOSE';
  Code:cipCLOSE;
  Extra:10;
  Gauche:0;
  Droite:Ofs(ipCONCAT)
 );

 ipDEC:NoeudInstrPasRec=(
  Nom:'DEC';
  Code:cipDEC;
  Extra:13;
  Gauche:0;
  Droite:0
 );

 ipDISABLE:NoeudInstrPasRec=(
  Nom:'DISABLE';
  Code:cipDISABLE;
  Extra:9;
  Gauche:0;
  Droite:0
 );

 ipDELETE:NoeudInstrPasRec=(
  Nom:'DELETE';
  Code:cipDELETE;
  Extra:14;
  Gauche:Ofs(ipDEC);
  Droite:Ofs(ipDISABLE)
 );

 ipCONTINUE:NoeudInstrPasRec=(
  Nom:'CONTINUE';
  Code:cipCONTINUE;
  Extra:12;
  Gauche:Ofs(ipCLOSE);
  Droite:Ofs(ipDELETE)
 );

 ipCLI:NoeudInstrPasRec=(
  Nom:'CLI';
  Code:cipCLI;
  Extra:9;
  Gauche:Ofs(ipBLOCKREAD);
  Droite:Ofs(ipCONTINUE)
 );

 ipERASE:NoeudInstrPasRec=(
  Nom:'ERASE';
  Code:cipERASE;
  Extra:21;
  Gauche:0;
  Droite:0
 );

 ipENABLE:NoeudInstrPasRec=(
  Nom:'ENABLE';
  Code:cipENABLE;
  Extra:19;
  Gauche:0;
  Droite:Ofs(ipERASE)
 );

 ipEXIT:NoeudInstrPasRec=(
  Nom:'EXIT';
  Code:cipEXIT;
  Extra:23;
  Gauche:0;
  Droite:0
 );

 ipFLUSH:NoeudInstrPasRec=(
  Nom:'FLUSH';
  Code:cipFLUSH;
  Extra:25;
  Gauche:0;
  Droite:0
 );

 ipFILLCHAR:NoeudInstrPasRec=(
  Nom:'FILLCHAR';
  Code:cipFILLCHAR;
  Extra:24;
  Gauche:Ofs(ipEXIT);
  Droite:Ofs(ipFLUSH)
 );

 ipEXCLUDE:NoeudInstrPasRec=(
  Nom:'EXCLUDE';
  Code:cipEXCLUDE;
  Extra:22;
  Gauche:Ofs(ipENABLE);
  Droite:Ofs(ipFILLCHAR)
 );

 ipGENINTERRUPT:NoeudInstrPasRec=(
  Nom:'GENINTERRUPT';
  Code:cipGENINTERRUPT;
  Extra:28;
  Gauche:0;
  Droite:0
 );

 ipGETMEM:NoeudInstrPasRec=(
  Nom:'GETMEM';
  Code:cipGETMEM;
  Extra:30;
  Gauche:0;
  Droite:0
 );

 ipGETDIR:NoeudInstrPasRec=(
  Nom:'GETDIR';
  Code:cipGETDIR;
  Extra:29;
  Gauche:Ofs(ipGENINTERRUPT);
  Droite:Ofs(ipGETMEM)
 );

 ipINC:NoeudInstrPasRec=(
  Nom:'INC';
  Code:cipINC;
  Extra:34;
  Gauche:0;
  Droite:0
 );

 ipINTR:NoeudInstrPasRec=(
  Nom:'INTR';
  Code:cipINTR;
  Extra:28;
  Gauche:0;
  Droite:0
 );

 ipINSERT:NoeudInstrPasRec=(
  Nom:'INSERT';
  Code:cipINSERT;
  Extra:36;
  Gauche:Ofs(ipINC);
  Droite:Ofs(ipINTR)
 );

 ipHALT:NoeudInstrPasRec=(
  Nom:'HALT';
  Code:cipHALT;
  Extra:32;
  Gauche:Ofs(ipGETDIR);
  Droite:Ofs(ipINSERT)
 );

 ipFREEMEM:NoeudInstrPasRec=(
  Nom:'FREEMEM';
  Code:cipFREEMEM;
  Extra:27;
  Gauche:Ofs(ipEXCLUDE);
  Droite:Ofs(ipHALT)
 );

 ipDISPOSE:NoeudInstrPasRec=(
  Nom:'DISPOSE';
  Code:cipDISPOSE;
  Extra:15;
  Gauche:Ofs(ipCLI);
  Droite:Ofs(ipFREEMEM)
 );

 ipMEMW:NoeudInstrPasRec=(
  Nom:'MEMW';
  Code:cipMEMW;
  Extra:31;
  Gauche:0;
  Droite:0
 );

 ipMEM:NoeudInstrPasRec=(
  Nom:'MEM';
  Code:cipMEM;
  Extra:30;
  Gauche:0;
  Droite:Ofs(ipMEMW)
 );

 ipMOVE:NoeudInstrPasRec=(
  Nom:'MOVE';
  Code:cipMOVE;
  Extra:33;
  Gauche:0;
  Droite:0
 );

 ipMOVERIGHT:NoeudInstrPasRec=(
  Nom:'MOVERIGHT';
  Code:cipMOVERIGHT;
  Extra:34;
  Gauche:0;
  Droite:0
 );

 ipMOVELEFT:NoeudInstrPasRec=(
  Nom:'MOVELEFT';
  Code:cipMOVELEFT;
  Extra:33;
  Gauche:Ofs(ipMOVE);
  Droite:Ofs(ipMOVERIGHT)
 );

 ipMKDIR:NoeudInstrPasRec=(
  Nom:'MKDIR';
  Code:cipMKDIR;
  Extra:32;
  Gauche:Ofs(ipMEM);
  Droite:Ofs(ipMOVELEFT)
 );

 ipNEW:NoeudInstrPasRec=(
  Nom:'NEW';
  Code:cipNEW;
  Extra:36;
  Gauche:0;
  Droite:0
 );

 ipPORTW:NoeudInstrPasRec=(
  Nom:'PORTW';
  Code:cipPORTW;
  Extra:38;
  Gauche:0;
  Droite:0
 );

 ipPORT:NoeudInstrPasRec=(
  Nom:'PORT';
  Code:cipPORT;
  Extra:37;
  Gauche:Ofs(ipNEW);
  Droite:Ofs(ipPORTW)
 );

 ipREAD:NoeudInstrPasRec=(
  Nom:'READ';
  Code:cipREAD;
  Extra:40;
  Gauche:0;
  Droite:0
 );

 ipRELEASE:NoeudInstrPasRec=(
  Nom:'RELEASE';
  Code:cipRELEASE;
  Extra:42;
  Gauche:0;
  Droite:0
 );

 ipREADLN:NoeudInstrPasRec=(
  Nom:'READLN';
  Code:cipREADLN;
  Extra:41;
  Gauche:Ofs(ipREAD);
  Droite:Ofs(ipRELEASE)
 );

 ipRANDOMIZE:NoeudInstrPasRec=(
  Nom:'RANDOMIZE';
  Code:cipRANDOMIZE;
  Extra:39;
  Gauche:Ofs(ipPORT);
  Droite:Ofs(ipREADLN)
 );

 ipMSDOS:NoeudInstrPasRec=(
  Nom:'MSDOS';
  Code:cipMSDOS;
  Extra:35;
  Gauche:Ofs(ipMKDIR);
  Droite:Ofs(ipRANDOMIZE)
 );

 ipREWRITE:NoeudInstrPasRec=(
  Nom:'REWRITE';
  Code:cipREWRITE;
  Extra:46;
  Gauche:0;
  Droite:0
 );

 ipRESET:NoeudInstrPasRec=(
  Nom:'RESET';
  Code:cipRESET;
  Extra:45;
  Gauche:0;
  Droite:Ofs(ipREWRITE)
 );

 ipRUNERROR:NoeudInstrPasRec=(
  Nom:'RUNERROR';
  Code:cipRUNERROR;
  Extra:48;
  Gauche:0;
  Droite:0
 );

 ipSETTEXTBUF:NoeudInstrPasRec=(
  Nom:'SETTEXTBUF';
  Code:cipSETTEXTBUF;
  Extra:50;
  Gauche:0;
  Droite:0
 );

 ipSEEK:NoeudInstrPasRec=(
  Nom:'SEEK';
  Code:cipSEEK;
  Extra:49;
  Gauche:Ofs(ipRUNERROR);
  Droite:Ofs(ipSETTEXTBUF)
 );

 ipRMDIR:NoeudInstrPasRec=(
  Nom:'RMDIR';
  Code:cipRMDIR;
  Extra:47;
  Gauche:Ofs(ipRESET);
  Droite:Ofs(ipSEEK)
 );

 ipSTR:NoeudInstrPasRec=(
  Nom:'STR';
  Code:cipSTR;
  Extra:52;
  Gauche:0;
  Droite:0
 );

 ipWRITE:NoeudInstrPasRec=(
  Nom:'WRITE';
  Code:cipWRITE;
  Extra:57;
  Gauche:0;
  Droite:0
 );

 ipVAL:NoeudInstrPasRec=(
  Nom:'VAL';
  Code:cipVAL;
  Extra:54;
  Gauche:Ofs(ipSTR);
  Droite:Ofs(ipWRITE)
 );

 ip_CF:NoeudInstrPasRec=(
  Nom:'_CF';
  Code:cip_CF;
  Extra:66;
  Gauche:0;
  Droite:0
 );

 ip_IF:NoeudInstrPasRec=(
  Nom:'_IF';
  Code:cip_IF;
  Extra:87;
  Gauche:0;
  Droite:0
 );

 ip_DF:NoeudInstrPasRec=(
  Nom:'_DF';
  Code:cip_DF;
  Extra:70;
  Gauche:Ofs(ip_CF);
  Droite:Ofs(ip_IF)
 );

 ipWRITELN:NoeudInstrPasRec=(
  Nom:'WRITELN';
  Code:cipWRITELN;
  Extra:58;
  Gauche:Ofs(ipVAL);
  Droite:Ofs(ip_DF)
 );

 ipSTI:NoeudInstrPasRec=(
  Nom:'STI';
  Code:cipSTI;
  Extra:51;
  Gauche:Ofs(ipRMDIR);
  Droite:Ofs(ipWRITELN)
 );

 ipRENAME:NoeudInstrPasRec=(
  Nom:'RENAME';
  Code:cipRENAME;
  Extra:43;
  Gauche:Ofs(ipMSDOS);
  Droite:Ofs(ipSTI)
 );

 InstrPas:NoeudInstrPasRec=(
  Nom:'MARK';
  Code:cipMARK;
  Extra:29;
  Gauche:Ofs(ipDISPOSE);
  Droite:Ofs(ipRENAME)
 );

Const
 craAH=4;                     { Registre ®AH¯ }
 craAL=0;                     { Registre ®AL¯ }
 craAX=0;                     { Registre ®AX¯ }
 craBH=7;                     { Registre ®BH¯ }
 craBL=3;                     { Registre ®BL¯ }
 craBP=5;                     { Registre ®BP¯ }
 craBX=3;                     { Registre ®BX¯ }
 craCH=5;                     { Registre ®CH¯ }
 craCL=1;                     { Registre ®CL¯ }
 craCR0=0;                    { Registre ®CR0¯ }
 craCR2=2;                    { Registre ®CR2¯ }
 craCR3=3;                    { Registre ®CR3¯ }
 craCR4=4;                    { Registre ®CR4¯ }
 craCS=1;                     { Registre ®CS¯ }
 craCX=1;                     { Registre ®CX¯ }
 craDH=6;                     { Registre ®DH¯ }
 craDI=7;                     { Registre ®DI¯ }
 craDL=2;                     { Registre ®DL¯ }
 craDR0=0;                    { Registre ®DR0¯ }
 craDR1=1;                    { Registre ®DR1¯ }
 craDR2=2;                    { Registre ®DR2¯ }
 craDR3=3;                    { Registre ®DR3¯ }
 craDR6=6;                    { Registre ®DR6¯ }
 craDR7=7;                    { Registre ®DR7¯ }
 craDS=3;                     { Registre ®DS¯ }
 craDX=2;                     { Registre ®DX¯ }
 craEAX=0;                    { Registre ®EAX¯ }
 craEBP=5;                    { Registre ®EBP¯ }
 craEBX=3;                    { Registre ®EBX¯ }
 craECX=1;                    { Registre ®ECX¯ }
 craEDI=7;                    { Registre ®EDI¯ }
 craEDX=2;                    { Registre ®EDX¯ }
 craES=0;                     { Registre ®ES¯ }
 craESI=6;                    { Registre ®ESI¯ }
 craESP=4;                    { Registre ®ESP¯ }
 craFS=4;                     { Registre ®FS¯ }
 craGS=5;                     { Registre ®GS¯ }
 craMM0=0;                    { Registre ®MM0¯ }
 craMM1=1;                    { Registre ®MM1¯ }
 craMM2=2;                    { Registre ®MM2¯ }
 craMM3=3;                    { Registre ®MM3¯ }
 craMM4=4;                    { Registre ®MM4¯ }
 craMM5=5;                    { Registre ®MM5¯ }
 craMM6=6;                    { Registre ®MM6¯ }
 craMM7=7;                    { Registre ®MM7¯ }
 craSI=6;                     { Registre ®SI¯ }
 craSP=4;                     { Registre ®SP¯ }
 craSS=2;                     { Registre ®SS¯ }
 craST=8;                     { Registre ®ST¯ }
 craST0=0;                    { Registre ®ST0¯ }
 craST1=1;                    { Registre ®ST1¯ }
 craST2=2;                    { Registre ®ST2¯ }
 craST3=3;                    { Registre ®ST3¯ }
 craST4=4;                    { Registre ®ST4¯ }
 craST5=5;                    { Registre ®ST5¯ }
 craST6=6;                    { Registre ®ST6¯ }
 craST7=7;                    { Registre ®ST7¯ }
 craTR3=3;                    { Registre ®TR3¯ }
 craTR4=4;                    { Registre ®TR4¯ }
 craTR5=5;                    { Registre ®TR5¯ }
 craTR6=6;                    { Registre ®TR6¯ }
 craTR7=7;                    { Registre ®TR7¯ }

  { Les constantes suivantes renferme l'arbre des }
  { registres assembleurs }

 raAL:NoeudRegAsmRec=(
  Nom:'AL';
  Code:craAL;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 raAH:NoeudRegAsmRec=(
  Nom:'AH';
  Code:craAH;
  Extra:8;
  Gauche:0;
  Droite:Ofs(raAL)
 );

 raBH:NoeudRegAsmRec=(
  Nom:'BH';
  Code:craBH;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 raBP:NoeudRegAsmRec=(
  Nom:'BP';
  Code:craBP;
  Extra:16;
  Gauche:0;
  Droite:0
 );

 raBL:NoeudRegAsmRec=(
  Nom:'BL';
  Code:craBL;
  Extra:8;
  Gauche:Ofs(raBH);
  Droite:Ofs(raBP)
 );

 raAX:NoeudRegAsmRec=(
  Nom:'AX';
  Code:craAX;
  Extra:16;
  Gauche:Ofs(raAH);
  Droite:Ofs(raBL)
 );

 raCH:NoeudRegAsmRec=(
  Nom:'CH';
  Code:craCH;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 raCR0:NoeudRegAsmRec=(
  Nom:'CR0';
  Code:craCR0;
  Extra:33;
  Gauche:0;
  Droite:0
 );

 raCL:NoeudRegAsmRec=(
  Nom:'CL';
  Code:craCL;
  Extra:8;
  Gauche:Ofs(raCH);
  Droite:Ofs(raCR0)
 );

 raCR3:NoeudRegAsmRec=(
  Nom:'CR3';
  Code:craCR3;
  Extra:33;
  Gauche:0;
  Droite:0
 );

 raCS:NoeudRegAsmRec=(
  Nom:'CS';
  Code:craCS;
  Extra:17;
  Gauche:0;
  Droite:0
 );

 raCR4:NoeudRegAsmRec=(
  Nom:'CR4';
  Code:craCR4;
  Extra:33;
  Gauche:Ofs(raCR3);
  Droite:Ofs(raCS)
 );

 raCR2:NoeudRegAsmRec=(
  Nom:'CR2';
  Code:craCR2;
  Extra:33;
  Gauche:Ofs(raCL);
  Droite:Ofs(raCR4)
 );

 raBX:NoeudRegAsmRec=(
  Nom:'BX';
  Code:craBX;
  Extra:16;
  Gauche:Ofs(raAX);
  Droite:Ofs(raCR2)
 );

 raDH:NoeudRegAsmRec=(
  Nom:'DH';
  Code:craDH;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 raDL:NoeudRegAsmRec=(
  Nom:'DL';
  Code:craDL;
  Extra:8;
  Gauche:0;
  Droite:0
 );

 raDI:NoeudRegAsmRec=(
  Nom:'DI';
  Code:craDI;
  Extra:16;
  Gauche:Ofs(raDH);
  Droite:Ofs(raDL)
 );

 raDR1:NoeudRegAsmRec=(
  Nom:'DR1';
  Code:craDR1;
  Extra:34;
  Gauche:0;
  Droite:0
 );

 raDR3:NoeudRegAsmRec=(
  Nom:'DR3';
  Code:craDR3;
  Extra:34;
  Gauche:0;
  Droite:0
 );

 raDR2:NoeudRegAsmRec=(
  Nom:'DR2';
  Code:craDR2;
  Extra:34;
  Gauche:Ofs(raDR1);
  Droite:Ofs(raDR3)
 );

 raDR0:NoeudRegAsmRec=(
  Nom:'DR0';
  Code:craDR0;
  Extra:34;
  Gauche:Ofs(raDI);
  Droite:Ofs(raDR2)
 );

 raDR7:NoeudRegAsmRec=(
  Nom:'DR7';
  Code:craDR7;
  Extra:34;
  Gauche:0;
  Droite:0
 );

 raDX:NoeudRegAsmRec=(
  Nom:'DX';
  Code:craDX;
  Extra:16;
  Gauche:0;
  Droite:0
 );

 raDS:NoeudRegAsmRec=(
  Nom:'DS';
  Code:craDS;
  Extra:17;
  Gauche:Ofs(raDR7);
  Droite:Ofs(raDX)
 );

 raEBP:NoeudRegAsmRec=(
  Nom:'EBP';
  Code:craEBP;
  Extra:32;
  Gauche:0;
  Droite:0
 );

 raECX:NoeudRegAsmRec=(
  Nom:'ECX';
  Code:craECX;
  Extra:32;
  Gauche:0;
  Droite:0
 );

 raEBX:NoeudRegAsmRec=(
  Nom:'EBX';
  Code:craEBX;
  Extra:32;
  Gauche:Ofs(raEBP);
  Droite:Ofs(raECX)
 );

 raEAX:NoeudRegAsmRec=(
  Nom:'EAX';
  Code:craEAX;
  Extra:32;
  Gauche:Ofs(raDS);
  Droite:Ofs(raEBX)
 );

 raDR6:NoeudRegAsmRec=(
  Nom:'DR6';
  Code:craDR6;
  Extra:34;
  Gauche:Ofs(raDR0);
  Droite:Ofs(raEAX)
 );

 raCX:NoeudRegAsmRec=(
  Nom:'CX';
  Code:craCX;
  Extra:16;
  Gauche:Ofs(raBX);
  Droite:Ofs(raDR6)
 );

 raEDX:NoeudRegAsmRec=(
  Nom:'EDX';
  Code:craEDX;
  Extra:32;
  Gauche:0;
  Droite:0
 );

 raESI:NoeudRegAsmRec=(
  Nom:'ESI';
  Code:craESI;
  Extra:32;
  Gauche:0;
  Droite:0
 );

 raES:NoeudRegAsmRec=(
  Nom:'ES';
  Code:craES;
  Extra:17;
  Gauche:Ofs(raEDX);
  Droite:Ofs(raESI)
 );

 raFS:NoeudRegAsmRec=(
  Nom:'FS';
  Code:craFS;
  Extra:18;
  Gauche:0;
  Droite:0
 );

 raMM0:NoeudRegAsmRec=(
  Nom:'MM0';
  Code:craMM0;
  Extra:64;
  Gauche:0;
  Droite:0
 );

 raGS:NoeudRegAsmRec=(
  Nom:'GS';
  Code:craGS;
  Extra:18;
  Gauche:Ofs(raFS);
  Droite:Ofs(raMM0)
 );

 raESP:NoeudRegAsmRec=(
  Nom:'ESP';
  Code:craESP;
  Extra:32;
  Gauche:Ofs(raES);
  Droite:Ofs(raGS)
 );

 raMM2:NoeudRegAsmRec=(
  Nom:'MM2';
  Code:craMM2;
  Extra:64;
  Gauche:0;
  Droite:0
 );

 raMM4:NoeudRegAsmRec=(
  Nom:'MM4';
  Code:craMM4;
  Extra:64;
  Gauche:0;
  Droite:0
 );

 raMM3:NoeudRegAsmRec=(
  Nom:'MM3';
  Code:craMM3;
  Extra:64;
  Gauche:Ofs(raMM2);
  Droite:Ofs(raMM4)
 );

 raMM6:NoeudRegAsmRec=(
  Nom:'MM6';
  Code:craMM6;
  Extra:64;
  Gauche:0;
  Droite:0
 );

 raSI:NoeudRegAsmRec=(
  Nom:'SI';
  Code:craSI;
  Extra:16;
  Gauche:0;
  Droite:0
 );

 raMM7:NoeudRegAsmRec=(
  Nom:'MM7';
  Code:craMM7;
  Extra:64;
  Gauche:Ofs(raMM6);
  Droite:Ofs(raSI)
 );

 raMM5:NoeudRegAsmRec=(
  Nom:'MM5';
  Code:craMM5;
  Extra:64;
  Gauche:Ofs(raMM3);
  Droite:Ofs(raMM7)
 );

 raMM1:NoeudRegAsmRec=(
  Nom:'MM1';
  Code:craMM1;
  Extra:64;
  Gauche:Ofs(raESP);
  Droite:Ofs(raMM5)
 );

 raSS:NoeudRegAsmRec=(
  Nom:'SS';
  Code:craSS;
  Extra:17;
  Gauche:0;
  Droite:0
 );

 raST0:NoeudRegAsmRec=(
  Nom:'ST0';
  Code:craST0;
  Extra:80;
  Gauche:0;
  Droite:0
 );

 raST:NoeudRegAsmRec=(
  Nom:'ST';
  Code:craST;
  Extra:80;
  Gauche:Ofs(raSS);
  Droite:Ofs(raST0)
 );

 raST2:NoeudRegAsmRec=(
  Nom:'ST2';
  Code:craST2;
  Extra:80;
  Gauche:0;
  Droite:0
 );

 raST4:NoeudRegAsmRec=(
  Nom:'ST4';
  Code:craST4;
  Extra:80;
  Gauche:0;
  Droite:0
 );

 raST3:NoeudRegAsmRec=(
  Nom:'ST3';
  Code:craST3;
  Extra:80;
  Gauche:Ofs(raST2);
  Droite:Ofs(raST4)
 );

 raST1:NoeudRegAsmRec=(
  Nom:'ST1';
  Code:craST1;
  Extra:80;
  Gauche:Ofs(raST);
  Droite:Ofs(raST3)
 );

 raST6:NoeudRegAsmRec=(
  Nom:'ST6';
  Code:craST6;
  Extra:80;
  Gauche:0;
  Droite:0
 );

 raTR3:NoeudRegAsmRec=(
  Nom:'TR3';
  Code:craTR3;
  Extra:35;
  Gauche:0;
  Droite:0
 );

 raST7:NoeudRegAsmRec=(
  Nom:'ST7';
  Code:craST7;
  Extra:80;
  Gauche:Ofs(raST6);
  Droite:Ofs(raTR3)
 );

 raTR5:NoeudRegAsmRec=(
  Nom:'TR5';
  Code:craTR5;
  Extra:35;
  Gauche:0;
  Droite:0
 );

 raTR7:NoeudRegAsmRec=(
  Nom:'TR7';
  Code:craTR7;
  Extra:35;
  Gauche:0;
  Droite:0
 );

 raTR6:NoeudRegAsmRec=(
  Nom:'TR6';
  Code:craTR6;
  Extra:35;
  Gauche:Ofs(raTR5);
  Droite:Ofs(raTR7)
 );

 raTR4:NoeudRegAsmRec=(
  Nom:'TR4';
  Code:craTR4;
  Extra:35;
  Gauche:Ofs(raST7);
  Droite:Ofs(raTR6)
 );

 raST5:NoeudRegAsmRec=(
  Nom:'ST5';
  Code:craST5;
  Extra:80;
  Gauche:Ofs(raST1);
  Droite:Ofs(raTR4)
 );

 raSP:NoeudRegAsmRec=(
  Nom:'SP';
  Code:craSP;
  Extra:16;
  Gauche:Ofs(raMM1);
  Droite:Ofs(raST5)
 );

 RegAsm:NoeudRegAsmRec=(
  Nom:'EDI';
  Code:craEDI;
  Extra:32;
  Gauche:Ofs(raCX);
  Droite:Ofs(raSP)
 );

Const

  { Les constantes suivantes renferme l'arbre des }
  { variables Pascal }

 vpBOOLEAN:NoeudVarPasRec=(
  Nom:'BOOLEAN';
  TypeDef:tBool;
  Size:SizeOf(Boolean);
  Gauche:0;
  Droite:0
 );

 vpBOOL:NoeudVarPasRec=(
  Nom:'BOOL';
  TypeDef:tBool;
  Size:SizeOf(Boolean);
  Gauche:0;
  Droite:Ofs(vpBOOLEAN)
 );

 vpCHAR:NoeudVarPasRec=(
  Nom:'CHAR';
  TypeDef:tChar;
  Size:SizeOf(Char);
  Gauche:0;
  Droite:0
 );

 vpCSTRING:NoeudVarPasRec=(
  Nom:'CSTRING';
  TypeDef:tCString;
  Size:256;
  Gauche:0;
  Droite:0
 );

 vpCHR:NoeudVarPasRec=(
  Nom:'CHR';
  TypeDef:tChar;
  Size:SizeOf(Char);
  Gauche:Ofs(vpCHAR);
  Droite:Ofs(vpCSTRING)
 );

 vpBYTE:NoeudVarPasRec=(
  Nom:'BYTE';
  TypeDef:tByte;
  Size:SizeOf(Byte);
  Gauche:Ofs(vpBOOL);
  Droite:Ofs(vpCHR)
 );

 vpLONGINT:NoeudVarPasRec=(
  Nom:'LONGINT';
  TypeDef:tLong;
  Size:SizeOf(LongInt);
  Gauche:0;
  Droite:0
 );

 vpPROCEDURE:NoeudVarPasRec=(
  Nom:'PROCEDURE';
  TypeDef:tProc;
  Size:4;
  Gauche:0;
  Droite:0
 );

 vpPOINTER:NoeudVarPasRec=(
  Nom:'POINTER';
  TypeDef:tPtr;
  Size:SizeOf(Pointer);
  Gauche:Ofs(vpLONGINT);
  Droite:Ofs(vpPROCEDURE)
 );

 vpSHORTINT:NoeudVarPasRec=(
  Nom:'SHORTINT';
  TypeDef:tShort;
  Size:SizeOf(ShortInt);
  Gauche:0;
  Droite:0
 );

 vpWORD:NoeudVarPasRec=(
  Nom:'WORD';
  TypeDef:tWord;
  Size:SizeOf(Word);
  Gauche:0;
  Droite:0
 );

 vpSTRING:NoeudVarPasRec=(
  Nom:'STRING';
  TypeDef:tString;
  Size:256;
  Gauche:Ofs(vpSHORTINT);
  Droite:Ofs(vpWORD)
 );

 vpPTR:NoeudVarPasRec=(
  Nom:'PTR';
  TypeDef:tPtr;
  Size:SizeOf(Pointer);
  Gauche:Ofs(vpPOINTER);
  Droite:Ofs(vpSTRING)
 );

 VarPas:NoeudVarPasRec=(
  Nom:'INTEGER';
  TypeDef:tInt;
  Size:SizeOf(Integer);
  Gauche:Ofs(vpBYTE);
  Droite:Ofs(vpPTR)
 );

